### ISSUE TITLE
Video IO (pyav) container reading issue

### ISSUE THREAD

**Issue by bjuncek** [pytorch/vision#1861] opened 2020-02-10 11:17 UTC
TV version: 0.6.0a0+e2573a7
AV version: '6.1.0'
--- 
when reading video using "read_video" function and pyav backend, I'm getting the following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-1373f6cf7aac> in <module>
----> 1 read_video("../videos/t_-Bqffbmkc.mp4", 0, 2, pts_unit="sec")

~/.conda/envs/new_ssl/lib/python3.7/site-packages/torchvision-0.6.0a0+e2573a7-py3.7-linux-x86_64.egg/torchvision/io/video.py in read_video(filename, start_pts, end_pts, pts_unit)
    260             info["audio_fps"] = container.streams.audio[0].rate
    261 
--> 262         container.close()
    263 
    264     vframes = [frame.to_rgb().to_ndarray() for frame in video_frames]

AttributeError: 'av.container.input.InputContainer' object has no attribute 'close'
```

the same command with video `reader_backend` works fine.
---
Minimal repro example:
```
import torchvision
import av
print(torchvision.__version__)
print(av.__version__)
torchvision.set_video_backend('pyav')
from torchvision.io import read_video
read_video("../videos/t_-Bqffbmkc.mp4", 0, 2, pts_unit="sec")
#throws error above
```
and similarly,
```
torchvision.set_video_backend('pyav')
from torchvision.io import read_video
read_video("../videos/t_-Bqffbmkc.mp4", 0, 2, pts_unit="sec")
```

works without any issues.

Any thoughts?

**Comment by bjuncek** [comment] 2020-02-10 11:18
(note, I can provide video in question if needed)

**Comment by bibsian** [comment] 2020-04-23 06:07
@bjuncek I just ran into this issue myself. Any workarounds you have other than editing the source code?

**Comment by bjuncek** [comment] 2020-04-23 09:05
Annoyingly, I found that the best/simplest way to sort it out is to force the `video-reader` backend :|

**Comment by fmassa** [comment] 2020-04-30 13:10
Hi,

The issue is that you need to have a newer version of PyAV, as `.close` was added in PyAV 6.2.0, see https://github.com/mikeboers/PyAV/blob/develop/CHANGELOG.rst#v620

Just update pyav and you should be fine.

I'm closing the issue but let me know if you have further issues

**Closed by fmassa** 2020-04-30 13:10 UTC
