### ISSUE TITLE
Densenet throws Output size too small error on 0.4.0

### ISSUE THREAD

**Issue by timonbimon** [pytorch/vision#1231] opened 2019-08-11 19:00 UTC
Hi there,

When trying to update torchvision from 0.3 to 0.4 one of my integration tests that tries to train a DenseNet121 now throws the following error:

```
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torchvision/models/densenet.py", line 155, in forward
    features = self.features(x)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 551, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (512x1x1). Calculated output size: (512x0x0). Output size is too small
```

We are using very small images (28x28x3), so I assume this is the cause, but everything was working fine with torchvision 0.3.0

I also already found this commit (https://github.com/pytorch/vision/commit/2cae9509932120553578bf41a93c930991cbd36b) that changes a few lines in the DenseNet implementation that seem shape/size related.

**Comment by fmassa** [comment] 2019-08-12 09:41
@timonbimon can you provide a minimum script reproducing the problem?

I've tried locally with a very recent PyTorch and TorchVision, and it works fine for me

```python
In [1]: import torch, torchvision

In [2]: m = torchvision.models.densenet121()

In [3]: i = torch.rand(2, 3, 28, 28)

In [4]: o = m(i)

In [5]: o.shape
Out[5]: torch.Size([2, 1000])

In [6]: torchvision.__version__
Out[6]: '0.3.0a0+f9788f3'

In [7]: torch.__version__
Out[7]: '1.2.0.dev20190704'
```

**Comment by timonbimon** [comment] 2019-08-12 09:50
here it is:

```
Python 3.7.3 (default, Apr 16 2019, 10:54:00)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torchvision
>>> m = torchvision.models.densenet121()
>>> i = torch.rand(2, 3, 28, 28)
>>> o = m(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torchvision/models/densenet.py", line 155, in forward
    features = self.features(x)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 551, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (512x1x1). Calculated output size: (512x0x0). Output size is too small
>>> torchvision.__version__
'0.4.0'
>>> torch.__version__
'1.2.0'
>>>
```

**Comment by fmassa** [comment] 2019-08-12 09:53
Ok, thanks for the repro, I'm having a closer look.

**Comment by timonbimon** [comment] 2019-08-12 09:54
weirdly enough:

```
Python 3.7.3 (default, Apr 16 2019, 10:54:00)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torchvision
>>> m = torchvision.models.densenet121()
>>> i = torch.rand(2, 3, 28, 28)
>>> o = m(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torchvision/models/densenet.py", line 155, in forward
    features = self.features(x)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/notepad-py3.7/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 551, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (512x1x1). Calculated output size: (512x0x0). Output size is too small
>>> torchvision.__version__
'0.4.0'
>>> torch.__version__
'1.2.0'
>>> i = torch.rand(2, 3, 29, 29)
>>> o = m(i)
>>>
```

size (29,29) seems to work just fine...

**Comment by fmassa** [comment] 2019-08-12 10:01
Ok, I managed to reproduce the problem.

This is a change in behavior that was introduced in PyTorch. I'm chasing the offending commit.

**Comment by fmassa** [comment] 2019-08-12 11:30
So, it seems that there was a change with the shape checks in the `AvgPool2d`.

For now, a possible workaround is to do
```python
for x in model.modules():
    if isinstance(x, nn.AvgPool2d):
        x.ceil_mode = True
```
and the results should work for you.

Now, the question is if it was a problem with the previous shape check or not, and this I should still investigate.

**Comment by fmassa** [comment] 2019-08-12 16:51
We need to further investigate if you were hitting a particular corner case (which was not expected to work, but just did), or if this is a regression in `AvgPool2d`.
I won't have the time to look more closely before a couple of weeks, so if anyone can have a look at this, it would be great.

cc @ezyang TL;DR: something in the behavior of `AvgPool2d` has changed between `'1.2.0.dev20190704'` and `1.2.0`, and I'm not sure if it's a regression or not.

**Comment by ezyang** [comment] 2019-08-12 18:53
We landed this emergency fix e6f9422acae251cf1e6a2680b98aef217b40d8f0 in 1.2.0; if it's not showing up on master this is the most likely culprit. I'm reinspecting the diff right now.

**Comment by ezyang** [comment] 2019-08-12 18:58
Actually, it's probably https://github.com/pytorch/pytorch/pull/22304

I haven't checked closely enough to tell if this is intended behavior or not

**Comment by fmassa** [comment] 2019-08-12 19:11
Note: I've just tested with PyTorch nightly from today, and the difference in behavior persists.

**Comment by ezyang** [comment] 2019-08-13 13:42
The call to F.avg_pool2d which fails has inputs `(torch.Size([2, 512, 1, 1]), 2, 2, 0, False, True, None)`

**Comment by ezyang** [comment] 2019-08-13 13:46
By the documentation: `H_out = floor((1 + 2*0 - 2) / 2 + 1)`, which should result in `H_out = 0`. So this behavior is expected per the documentation. Use of `ceil_mode` here seems like the appropriate resolution.

**Closed by ezyang** 2019-08-13 13:46 UTC
Labels: help wanted, module: models, needs reproduction, topic: classification

**Comment by timonbimon** [comment] 2019-08-13 13:58
thanks for investigating! :) 

I ended up just re-sizing the images in our integration test to 29 instead of 28 (which feels a little arbitrary but so be it), since we anyways only use images that small in our tests and not during training or inference.
