### ISSUE TITLE
RuntimeError: No such operator image::read_file on Docker

### ISSUE THREAD

**Issue by moskomule** [pytorch/vision#4181] opened 2021-07-15 03:07 UTC
## 🐛 Bug

In a Docker environment, `torch.io.read_file` causes `RuntimeError: No such operator image::read_file`.

### 1. Setup a container

I used the following Docker file.

```dockerfile
FROM nvidia/cuda:11.0-base-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -qq \
    && apt install -y -qq \
    apt-utils \
    bzip2 \
    build-essential \
    cmake \
    curl \
    git \
    libncurses5-dev \
    libncursesw5-dev \
    libboost-all-dev \
    locales \
    nasm \
    ruby \
    sudo \
    swig \
    unzip \
    wget \
    zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDADIR ${HOME}/.miniconda
RUN cd ${HOME} \
    && wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p ${CONDADIR} \
    && rm miniconda.sh
```

```
docker build -t test .
docker run --rm -it test
# in the launched container
export PATH=.miniconda/bin:$PATH
conda create -n test python=3.9 -y
source activate test
conda install -c pytorch -c nvidia -c conda-forge pytorch torchvision cudatoolkit=11.1 numpy -y # another issue, but numpy is not automatically installed as a dependency
```

### Run the following

```python
import torchvision
torchvision.io.read_file(".")
# RuntimeError: No such operator image::read_file
```

## Environment

`collect_env.py` collects the following information (Docker v20.10.7).

```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0                     9_mkl    conda-forge
[conda] libcblas                  3.9.0                     9_mkl    conda-forge
[conda] liblapack                 3.9.0                     9_mkl    conda-forge
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.21.0           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchvision               0.10.0               py39_cu111    pytorch
```

## Additional context

I could not reproduce this issue in a non-Docker environment. A nightly build resolved this issue.

**Comment by andfoy** [comment] 2021-07-21 16:29
Hi @moskomule, thanks for reaching out, what happens if you run the python interpreter with `LD_DEBUG=all`?

**Comment by moskomule** [comment] 2021-07-22 08:09
Hi @andfoy, it produces a very long output. Which part do I need to report here?

**Comment by moskomule** [comment] 2021-07-22 09:15
Hi @andfoy!

`LD_DEBUG=all python` produces a log of 800MB, so I uploaded it to Google Drive.
https://drive.google.com/file/d/1ZYgHjxhY9iWMxjBm0tztsZQbE9e23-M0/view?usp=sharing
I hope it will help you to investigate the issue.

**Comment by h-vetinari** [comment] 2021-08-05 19:39
Hitting this issue as well in https://github.com/conda-forge/allennlp-models-feedstock/pull/12

**Comment by fmassa** [comment] 2021-08-12 12:05
@andfoy did you have the time to investigate this issue?

**Comment by andfoy** [comment] 2021-08-12 21:12
@fmassa, I'll reproduce the docker file on my local machine to see if there are missing dependencies, that could be the only explanation

**Comment by andfoy** [comment] 2021-08-17 23:48
The problem is related to the jpeg version being installed, by looking at the `ldd` output over `image.so` it looks that the torchvision distribution is linking against `libjpeg.so.8`, whereas the conda solver is installing `jpeg-9b-h024ee3a_2`, which provides `libjpeg.so.9`

```bash
(test) root@a29d38ca2593:/.miniconda/envs/test/lib/python3.9/site-packages/torchvision# ldd image.so 
	linux-vdso.so.1 (0x00007ffd555c6000)
	libpng16.so.16 => /.miniconda/envs/test/lib/python3.9/site-packages/torchvision/./../../../libpng16.so.16 (0x00007f17902f9000)
	libjpeg.so.8 => not found
	...
```

```bash
(test) root@a29d38ca2593:/.miniconda/envs/test/lib/python3.9/site-packages/torchvision# ls /.miniconda/envs/test/lib/libjpeg.
libjpeg.a         libjpeg.la        libjpeg.so        libjpeg.so.9      libjpeg.so.9.2.0
```

This is an issue that requires a recompilation of torchvision to link against `jpeg 9b` and pinning this version in the recipe

**Comment by datumbox** [comment] 2021-08-18 08:26
@andfoy FYI we are about to remove the jpeg pinning. We got a working solution and it should be merged soon.

**Comment by datumbox** [comment] 2021-08-19 14:37
Could you check again using the latest master?

**Comment by moskomule** [comment] 2021-08-23 03:06
Hi @datumbox, `pytorch-nightly/linux-64::pytorch-1.10.0.dev20210822-py3.9_cuda11.1_cudnn8.0.5_0`, the latest nightliy build as of today, causes no problem. Thanks.

**Closed** 2021-08-23 08:50 UTC
Labels: bug, module: io

**Comment by saswatpp** [comment] 2021-09-02 21:03
Hi this error still persists in `pytorch 1.10.0.dev20210902` (cpu only version) and `torchvision 0.11.0a0+ad3c3f7`. The environment is WSL. 

I was trying to build the docs. Torchvision was installed using :

```python
python setup.py develop
```

Exact Error :
```python3
make html
Running Sphinx v3.5.4
loading intersphinx inventory from https://docs.python.org/objects.inv...
loading intersphinx inventory from https://pytorch.org/docs/stable/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://pillow.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for auto_examples... [ 25%] plot_scripted_tensor_transforms.py
Warning, treated as error:
/mnt/g/devel/vision/gallery/plot_scripted_tensor_transforms.py failed to execute correctly: Traceback (most recent call last):
  File "/mnt/g/devel/vision/gallery/plot_scripted_tensor_transforms.py", line 52, in <module>
    dog1 = read_image(str(Path('assets') / 'dog1.jpg'))
  File "/mnt/g/devel/vision/torchvision/io/image.py", line 222, in read_image
    data = read_file(path)
  File "/mnt/g/devel/vision/torchvision/io/image.py", line 42, in read_file
    data = torch.ops.image.read_file(path)
  File "/home/konoha/.conda/envs/vision/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file

Makefile:41: recipe for target 'html' failed
make: *** [html] Error 2
```
