### ISSUE TITLE
CPU unit tests are failing in vision nightly builds

### ISSUE THREAD

**Issue by izaitsevfb** [pytorch/vision#8051] opened 2023-10-17 20:41 UTC
### 🐛 Describe the bug

HUD: https://hud.pytorch.org/hud/pytorch/vision/nightly/1?per_page=50&name_filter=tests%20%2F%20unittests

Looks like the same issue across platforms:
```
2023-10-16T11:57:47.9045908Z [31mFAILED[0m test/test_utils.py::[1mtest_draw_boxes[0m - AssertionError: Tensor-likes are not equal!
2023-10-16T11:57:47.9046508Z 
2023-10-16T11:57:47.9046642Z Mismatched elements: 240 / 30000 (0.8%)
2023-10-16T11:57:47.9047134Z Greatest absolute difference: 251 at index (0, 10, 5)
2023-10-16T11:57:47.9047689Z Greatest relative difference: inf at index (0, 8, 4)
2023-10-16T11:57:47.9048831Z [31m= [31m[1m1 failed[0m, [32m21402 passed[0m, [33m16844 skipped[0m, [33m1 xfailed[0m, [33m251 warnings[0m[31m in 1206.38s (0:20:06)[0m[31m =[0m
2023-10-16T11:57:47.9062170Z ##[error]Process completed with exit code 1.
```

cc @NicolasHug @pmeier  @atalman 

### Versions

null

**Comment by pmeier** [comment] 2023-10-17 20:48
We haven't merged anything the last few days. Meaning, this likely comes from core. Let me dig and see if I can find an offending PR.

**Comment by pmeier** [comment] 2023-10-17 20:52
Could also come from Pillow. Error points to

https://github.com/pytorch/vision/blob/1d6f78755bafa412ab19d0fa12654444b02d362b/test/test_utils.py#L108-L111

and `Pillow==10.1` was released two days ago.

**Comment by pmeier** [comment] 2023-10-17 21:00
Can reproduce with `Pillow==10.1.0`.

**Comment by pmeier** [comment] 2023-10-17 21:23
The default font has changed. See python-pillow/Pillow#7354

reference / new

![reference](https://github.com/pytorch/vision/assets/6849766/a6d79e70-d0a8-491b-a736-28e13b40da52) ![new](https://github.com/pytorch/vision/assets/6849766/a3d0523e-2bd9-40ba-b9bd-56866727c8ee)

**Comment by pmeier** [comment] 2023-10-17 21:35
There currently seems to be no way to force the old font. I'll ask for clarification there. In the mean time, we could temporarily pin to `pillow<10.1` until we have a plan.

**Closed as completed** 2023-10-18 17:16 UTC
Labels: dependency issue
