### ISSUE TITLE
Bug of DataLoader and FashionMNIST

### ISSUE THREAD

**Issue by leftthomas** [pytorch/vision#406] opened 2018-02-02 16:18 UTC
I used torchnet to train my model with six datasets, the data load is implemented with PyTorch API torch.utils.data.DataLoader and torchvision.datasets.
When I train with FashionMNIST, I found the test data is the MNIST test datas, not the FashionMNIST test datas, why this happen?
below is  my code:
```
# main.py
import utils
engine.train(processor, utils.get_iterator(True, DATA_TYPE, BATCH_SIZE,
USE_DATA_AUGMENTATION), maxepoch=NUM_EPOCHS,optimizer=optimizer)
......
train_images, _ = next(iter(utils.get_iterator(True, DATA_TYPE, 16, USE_DATA_AUGMENTATION)))
test_images, _ = next(iter(utils.get_iterator(False, DATA_TYPE, 16, USE_DATA_AUGMENTATION)))
train_image_logger.log(make_grid(train_images, nrow=4, normalize=True).numpy())
test_image_logger.log(make_grid(test_images, nrow=4, normalize=True).numpy())
......
# utils.py
from torch.utils.data import DataLoader
from torchvision.datasets import CIFAR100, CIFAR10, MNIST, FashionMNIST, STL10, SVHN
data_set = {'MNIST': MNIST, 'FashionMNIST': FashionMNIST, 'SVHN': SVHN, 'CIFAR10': CIFAR10, 'CIFAR100': CIFAR100, 'STL10': STL10}
......
def get_iterator(mode, data_type, batch_size, use_data_augmentation):
      ......
      if (data_type == 'STL10') or (data_type == 'SVHN'):
             data = data_set[data_type](root='data/' + data_type, split='train' if mode else 'test',
                                   transform=transform_train if mode else transform_test, download=True)
      else:
            data = data_set[data_type](root='data/' + data_type, train=mode,
                                   transform=transform_train if mode else transform_test, download=True)
      return DataLoader(dataset=data, batch_size=batch_size, shuffle=mode, num_workers=4)
```
then I run 
<img width="1272" alt="qq20180202-234737 2x" src="https://user-images.githubusercontent.com/9991443/35743141-94f87cbe-0877-11e8-90f0-bc065b3eb977.png">
but when I open visdom to see the images, it got this:

<img width="829" alt="qq20180202-234657 2x" src="https://user-images.githubusercontent.com/9991443/35743158-a6fd05b0-0877-11e8-9997-d86f18da3f4a.png">

**Comment by vishwakftw** [comment] 2018-02-04 11:52
The file names are the same for both MNIST and FashionMNIST. Could you try storing these datasets in different directories?

**Comment by leftthomas** [comment] 2018-02-04 12:18
@vishwakftw  the downloaded url is different, and I store them on different root directories, that can be inferenced from my code, it’s “data/datatype” which datatype comed from console input.

**Comment by vishwakftw** [comment] 2018-02-10 16:05
Sorry about that. I am not able to reproduce the error.

**Comment by fmassa** [comment] 2018-02-12 09:21
@leftthomas I have also just downloaded the datasets from a fresh install and everything was working fine.
I suspect that at some point you downloaded the files in the same folder, and the `test.pt` file that was degenerated got overwritten.

Please try deleting those files and downloading them again, by putting since the beginning them in different folders.

I'm closing the issue, but please let us know if you still face this issue.

**Closed by fmassa** 2018-02-12 09:21 UTC

**Comment by leftthomas** [comment] 2018-02-12 11:37
@fmassa, I have tried to delete the files and download again, but it still behaves like that, I debug that for a long time, but I can't figure out why that happened.  And according to my code I have posted, the folder is  inferred from the console input `data_type `, it is different for MNIST and FashionMNIST.
The  MNIST and FashionMNIST class is instanced on run time, maybe the problem happen because I used the `dict` to instance the dataset class?
Here are my code files:
[codes.zip](https://github.com/pytorch/vision/files/1716142/codes.zip)

**Comment by fmassa** [comment] 2018-02-12 12:13
I still suspect that the files are wrong.
Can you check if the sizes of `MNIST/test.pt` and `FashionMNIST/test.pt` are the same? If yes, then there is your problem. The `download=True` flag only downloads the file again [if it doesn't exist already](https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L99-L100).

If the files are indeed different, then there is a bug in your code, but I couldn't spot it from a quick look.

**Comment by leftthomas** [comment] 2018-02-12 13:02
@fmassa , I have checked the size of `test.pt`, whenever the download files is right or wrong, they are all equal to 7,920,424 bytes.

**Comment by fmassa** [comment] 2018-02-12 13:42
Sorry, I should have mentioned that you should also check if the hash of the files are the same or different (because the sizes in this case can be the same because they have the same number of images and sizes).

Something like
```
md5sum MNIST/test.pt
md5sum FashionMNIST/test.pt
```

If those are the same, then you should try downloading the original files again, maybe from your browser?

**Comment by leftthomas** [comment] 2018-02-12 14:22
@fmassa I downloaded the fashionmnist dataset from browser to work with my experiment, but it’s a temporary solution, I can’t figure out why the download code didn’t work, I have debugged for that, and the url is right.

**Comment by fmassa** [comment] 2018-02-12 14:37
Did you also delete the downloaded files from the folder (and not only `test.pt`)?
I think that was the problem.
To make sure that the problem was indeed in there, you could try running your code but adding the source directory to a newly created one
```
mkdir new_source
# run code saving in `new_source` instead of source
```

**Comment by leftthomas** [comment] 2018-02-12 23:48
@fmassa I have deleted all the downloaded files, not just the `test.pt` file, and I also run the code on three computer, but it's odd when I run the code on my Mac, it wouldn't encounter the problem, when I run the code on my Ubuntu, it encounters the problem.

**Comment by fmassa** [comment] 2018-02-13 10:53
I have no idea what might be wrong there. I have run the code on an Ubuntu and it worked fine, so there might be something fishy going on on your machine.
