### ISSUE TITLE
Downloading MNIST dataset with torchvision gives HTTP Error 403

### ISSUE THREAD

**Issue by Borda** [pytorch/vision#1938] opened 2020-03-04 10:36 UTC
## 🐛 Bug

I'm getting a 403 error when I try to download MNIST dataset with `torchvision` 0.4.2.

## To Reproduce

```
../.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py:68: in __init__
    self.download()
../.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py:135: in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename)
../.local/lib/python3.6/site-packages/torchvision/datasets/utils.py:248: in download_and_extract_archive
    download_url(url, download_root, filename, md5)
../.local/lib/python3.6/site-packages/torchvision/datasets/utils.py:96: in download_url
    raise e
../.local/lib/python3.6/site-packages/torchvision/datasets/utils.py:84: in download_url
    reporthook=gen_bar_updater()
/usr/local/lib/python3.6/urllib/request.py:248: in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
/usr/local/lib/python3.6/urllib/request.py:223: in urlopen
    return opener.open(url, data, timeout)
/usr/local/lib/python3.6/urllib/request.py:532: in open
    response = meth(req, response)
/usr/local/lib/python3.6/urllib/request.py:642: in http_response
    'http', request, response, code, msg, hdrs)
/usr/local/lib/python3.6/urllib/request.py:570: in error
    return self._call_chain(*args)
/usr/local/lib/python3.6/urllib/request.py:504: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <urllib.request.HTTPDefaultErrorHandler object at 0x7efbf9edaac8>
req = <urllib.request.Request object at 0x7efbf9eda8d0>
fp = <http.client.HTTPResponse object at 0x7efbf9edaf98>, code = 403
msg = 'Forbidden', hdrs = <http.client.HTTPMessage object at 0x7efbf9ea22b0>

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Environment

* torch==1.3.1     
* torchvision==0.4.2

## Additional context

https://app.circleci.com/jobs/github/PyTorchLightning/pytorch-lightning/6877

**Comment by fmassa** [comment] 2020-03-04 12:40
Thanks for reporting! I can reproduce the issue locally, and downloading from the browser works.

I don't yet know what the root cause is though.

**Comment by fmassa** [comment] 2020-03-04 12:52
I think we might need to pass `header` in the download_url` function https://github.com/pytorch/vision/blob/c3e2b018517dedcbda18462f5d3e62e1fd913003/torchvision/datasets/utils.py#L59-L100 according to https://stackoverflow.com/questions/13303449/urllib2-httperror-http-error-403-forbidden

cc @cpuhrsch @vincentqb @zhangguanheng66 for awareness

**Comment by soumith** [comment] 2020-03-04 12:53
this is because the download links for mnist at https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py#L33-L36 are hosted on yann.lecun.com and that server has moved under CloudFlare protection.

@fmassa we need to maybe mirror and change the URLs to maybe the PyTorch S3 bucket or something

**Comment by Borda** [comment] 2020-03-04 12:57
so could we make a hot-fix somehow?

**Comment by fmassa** [comment] 2020-03-04 12:59
@Borda I haven't tried the current hotfix I mentioned, but I think it might be possible, would you be able to try it and send a PR? Otherwise I'll look into it early next week (I'm working towards ECCV deadline tomorrow)

And I would rather avoid hosting the datasets ourselves, as this would give precedence on us storing the datasets.

**Comment by eduardo4jesus** [comment] 2020-03-04 14:25
Anyway to have a quick fix without using the master?
I am concerned about the potential changes I have to do in my code for going from the version I am using (1.4.0) and the master.

**Comment by mvelebit** [comment] 2020-03-04 14:45
@eduardo4jesus You can explicitly add headers as stated above, something alike:
`opener = urllib.request.URLopener()
            opener.addheader('User-Agent', some_user_agent)
            opener.retrieve(
                url, fpath,
                reporthook=gen_bar_updater()
            )`
Worked for me.

**Comment by nvcastet** [comment] 2020-03-04 18:44
To make it work for python 2 as well:
```
import urllib
try:
    # For python 2
    class AppURLopener(urllib.FancyURLopener):
        version = "Mozilla/5.0"

    urllib._urlopener = AppURLopener()
except AttributeError:
    # For python 3
    opener = urllib.request.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    urllib.request.install_opener(opener)
```

**Comment by joergsimon** [comment] 2020-03-04 19:18
so for python 3 I now use the following snipplet:

`from torchvision import datasets
import torchvision.transforms as transforms
import urllib

num_workers = 0
batch_size = 20
basepath = 'some/base/path'
transform = transforms.ToTensor()

def set_header_for(url, filename):
    opener = urllib.request.URLopener()
    opener.addheader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36')
    opener.retrieve(
    url, f'{basepath}/{filename}')

set_header_for('http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'train-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz', 'train-labels-idx1-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz', 't10k-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz', 't10k-labels-idx1-ubyte.gz')
train_data = datasets.MNIST(root='data', train=True,
                                   download=True, transform=transform)
test_data = datasets.MNIST(root='data', train=False,
                                  download=False, transform=transform)`

You would need to modify the `basepath` variable of course

**Comment by fatihbeyhan** [comment] 2020-03-04 20:13
I've just got the same problem. Waiting for the answer without changing codes... (ROOKIE ALERT)

**Comment by knamdar** [comment] 2020-03-05 01:17
> I've just got the same problem. Waiting for the answer without changing codes... (ROOKIE ALERT)

Clone this to your working dir:
https://github.com/knamdar/data

**Comment by n-makarin** [comment] 2020-03-05 04:24
I've the same issue when I'm trying to get datasets:
`import torch
import torchvision
from torchvision import transforms, datasets

train = datasets.MNIST("", train=True, download=True,
                       transform=transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train=False, download=True,
                      transform=transforms.Compose([transforms.ToTensor()]))`

**Comment by n-makarin** [comment] 2020-03-05 04:25
I've the same issue when I'm trying to get datasets:
`
import torch
import torchvision
from torchvision import transforms, datasets

train = datasets.MNIST("", train=True, download=True,
transform=transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train=False, download=True,
transform=transforms.Compose([transforms.ToTensor()]))
`

**Comment by n-makarin** [comment] 2020-03-05 04:26
I've the same issue when I'm trying to get datasets:
```
import torch
import torchvision
from torchvision import transforms, datasets

train = datasets.MNIST("", train=True, download=True,
transform=transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train=False, download=True,
transform=transforms.Compose([transforms.ToTensor()]))
```

**Comment by joergsimon** [comment] 2020-03-05 12:34
The problem ist that Yann LeCun’s side changed hoster if I got it right, and this one checks if the HTTP headers are set.

I currently work around with the following code:


from torchvision import datasets
import torchvision.transforms as transforms
import urllib

num_workers = 0
batch_size = 20
basepath = 'some/base/path'
transform = transforms.ToTensor()

def set_header_for(url, filename):
    opener = urllib.request.URLopener()
    opener.addheader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36')
    opener.retrieve(
    url, f'{basepath}/{filename}')

set_header_for('http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'train-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz', 'train-labels-idx1-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz', 't10k-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz', 't10k-labels-idx1-ubyte.gz')
train_data = datasets.MNIST(root='data', train=True,
                                   download=True, transform=transform)
test_data = datasets.MNIST(root='data', train=False,
                                  download=False, transform=transform)
You need to change base path of course

**Comment by eduardo4jesus** [comment] 2020-03-05 16:28
> from six.moves import urllib
> opener = urllib.request.build_opener()
> opener.addheaders = [('User-agent', 'Mozilla/5.0')]
> urllib.request.install_opener(opener)

@nvcastet, Thank you so much for the clarification. At that point I misunderstood that I would have to go into `Torchvision` library and change one of its internal files.

> vision/torchvision/datasets/utils.py

What would be not a smooth move on Colab/Kaggle.

**Comment by fmassa** [comment] 2020-03-05 16:51
This should have been fixed now, there is no need to update torchvision.
This was fixed on the server hosting the dataset.

As such, I'm closing this issue but let us know if you still face this issue.

**Closed by fmassa** 2020-03-05 16:51 UTC
Labels: bug, help wanted, module: datasets

**Comment by mihai-db** [comment] 2021-03-03 12:52
still happens

**Comment by mlelarge** [comment] 2021-03-03 15:32
Same on Colab:
```
import torchvision
import torchvision.transforms as transforms
root_dir = './data/MNIST/'
torchvision.datasets.MNIST(root=root_dir,download=True)
```
I get: HTTPError: HTTP Error 403: Forbidden

`torchvision.__version__` -> 0.8.2+cu101

**Comment by kesterlester** [comment] 2021-03-03 15:40
I also just got this problem.

**Comment by m-elmi** [comment] 2021-03-03 15:49
> I also just got this problem.

Same here. It was working just fine this morning.

**Comment by kesterlester** [comment] 2021-03-03 15:51
I think perhaps we should start a new issue (that links back to this one) as this one is closed and may get no attention. So far as I can see no one has made a new one yet, so I will try to create one now, referring back here.

**Comment by mlelarge** [comment] 2021-03-03 15:57
Thanks @kesterlester 
I did put MNIST on my webpage: `wget www.di.ens.fr/~lelarge/MNIST.tar.gz` if you need it!

**Comment by andresgtn** [comment] 2021-03-03 19:13
copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...

from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)

`from six.moves import urllib`

`opener = urllib.request.build_opener()`

**Comment by rodrsilv-stark** [comment] 2021-03-04 16:07
> copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> 
> `from six.moves import urllib`
> `opener = urllib.request.build_opener()`
> `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> `urllib.request.install_opener(opener)`

Very good!, worked fine.

**Comment by madhavajay** [comment] 2021-03-05 01:03
![image](https://user-images.githubusercontent.com/2882739/110051907-62c23200-7da2-11eb-95c3-f92acb69425f.png)

**Comment by fmassa** [comment] 2021-03-05 12:11
FYI we changed torchvision to try to fix this, and the fix should be present in the latest release (from yesterday), with a fix in https://github.com/pytorch/vision/pull/3499

**Comment by scaomath** [comment] 2021-03-05 19:40
> copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> 
> `from six.moves import urllib`
> `opener = urllib.request.build_opener()`
> `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> `urllib.request.install_opener(opener)`

Works like a charm, saved my (insert whatever appropriate word) as I rely on fetching MNIST remotely to teach college kids...

**Comment by BernardoOlisan** [comment] 2021-03-06 23:23
> copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> 
> `from six.moves import urllib`
> `opener = urllib.request.build_opener()`
> `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> `urllib.request.install_opener(opener)`

Dude this is insane you save my day, thank you a lot bro!!

**Comment by Flock1** [comment] 2021-03-11 05:50
> copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> 
> `from six.moves import urllib`
> `opener = urllib.request.build_opener()`
> `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> `urllib.request.install_opener(opener)`

This worked. I am new to this, so can you tell me what does this piece of code does?

**Comment by HugoSchmutz** [comment] 2021-03-11 14:27
> copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> 
> `from six.moves import urllib`
> `opener = urllib.request.build_opener()`
> `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> `urllib.request.install_opener(opener)`

Didn't work for me on Colab today

**Comment by mlelarge** [comment] 2021-03-11 14:47
You can download it from my webpage:
https://gist.github.com/mlelarge/60ddefa9e16bc06f7f4fc7bff769bdb1

**Comment by junpuf** [comment] 2021-03-11 19:37
Did anyone got `urllib.error.HTTPError: HTTP Error 503: Service Unavailable` last night?

**Comment by ChengguiSun** [comment] 2021-03-11 21:34
> > copy this snippet at the top of your notebook, run it, and then just load your datasets as usual...
> > `from six.moves import urllib`
> > `opener = urllib.request.build_opener()`
> > `opener.addheaders = [('User-agent', 'Mozilla/5.0')]`
> > `urllib.request.install_opener(opener)`
> 
> Didn't work for me on Colab today

Didn't work for me either

**Comment by BernardoOlisan** [comment] 2021-03-12 03:33
> Did anyone got `urllib.error.HTTPError: HTTP Error 503: Service Unavailable` last night?

Yep yesterday it was working for me but now is not, I dont know what happend, is there a solution for this?

**Comment by alisterburt** [comment] 2021-03-12 08:35
@BernardoOlisan @ChengguiSun the solution from @mlelarge works great, the following worked for me in a notebook

```python
!wget www.di.ens.fr/~lelarge/MNIST.tar.gz
!tar -zxvf MNIST.tar.gz

from torchvision.datasets import MNIST
from torchvision import transforms

mnist_train = MNIST('./', download=False,
                    transform=transforms.Compose([
                        transforms.ToTensor(),
                    ]), train = True)
```

**Comment by HugoSchmutz** [comment] 2021-03-12 08:54
Thank you ! @mlelarge and @alisterburt

**Comment by BernardoOlisan** [comment] 2021-03-12 14:01
> ```python
> !wget www.di.ens.fr/~lelarge/MNIST.tar.gz
> !tar -zxvf MNIST.tar.gz
> ```

nope still got the exact same error

**Comment by alisterburt** [comment] 2021-03-12 14:05
@BernardoOlisan do you get the same error when trying to download from that link in a browser? Just tried again locally and all worked fine...

**Comment by scaomath** [comment] 2021-03-12 19:18
> > ```python
> > !wget www.di.ens.fr/~lelarge/MNIST.tar.gz
> > !tar -zxvf MNIST.tar.gz
> > ```
> 
> nope still got the exact same error

You have to have a folder called `MNIST/raw/` in the folder with your dataset script or notebook
```python
torchvision.datasets.MNIST(root='./', download=False,
                    transform=transforms.Compose([
                        transforms.ToTensor(),
                    ]), train=True)
```
If you have your code
```python
torchvision.datasets.MNIST(root='./data', download=False,
                    transform=transforms.Compose([
                        transforms.ToTensor(),
                    ]), train=True)
```
then the folder has to be structured as 

```bash
├── data
 │   ├── MNIST
 │                ├── processed
 │               └── raw
└── Python script
```

**Comment by andrewssobral** [comment] 2021-03-12 19:41
The solution proposed by @mlelarge works fine for me, but in my case I have:
```
# For new versions of TorchVision
wget -O MNIST.tar.gz https://activeeon-public.s3.eu-west-2.amazonaws.com/datasets/MNIST.new.tar.gz

# For old versions of TorchVision (<= 1.0.1*)
wget -O MNIST.tar.gz https://activeeon-public.s3.eu-west-2.amazonaws.com/datasets/MNIST.old.tar.gz

tar -zxvf MNIST.tar.gz
```
then, I do:
```
train_loader = torch.utils.data.DataLoader(
  datasets.MNIST('./', train=True, download=False,
                 transform=transforms.Compose([
                     transforms.ToTensor(),
                     transforms.Normalize((0.1307,), (0.3081,))
                 ])),
  batch_size=args.batch_size, shuffle=True, **kwargs)
```
and everything works well.

**Comment by fmassa** [comment] 2021-03-12 21:11
This should be fixed (again) in the next torchvision nightly, and the fix will be present in the next minor release of torchvision, which should be out soon.

See https://github.com/pytorch/vision/pull/3544 for more details

**Comment by andrewssobral** [comment] 2021-03-12 22:51
Perfect, thank you @fmassa !

**Comment by ChengguiSun** [comment] 2021-03-17 06:05
@alisterburt, thank you. I used that solution too. Sometimes it works, sometimes it doesn't. It works for me tonight. It's just very slow to download the dataset.

> @BernardoOlisan @ChengguiSun the solution from @mlelarge works great, the following worked for me in a notebook
> 
> ```python
> !wget www.di.ens.fr/~lelarge/MNIST.tar.gz
> !tar -zxvf MNIST.tar.gz
> 
> from torchvision.datasets import MNIST
> from torchvision import transforms
> 
> mnist_train = MNIST('./', download=False,
>                     transform=transforms.Compose([
>                         transforms.ToTensor(),
>                     ]), train=True)
> ```

**Comment by mohamed-180** [comment] 2021-03-21 09:47
try this 

```
from torchvision import datasets
datasets.MNIST(".", download=True)

```

**Comment by scaomath** [comment] 2021-03-25 13:32
> @alisterburt, thank you. I used that solution too. Sometimes it works, sometimes it doesn't. It works for me tonight. It's just very slow to download the dataset.

Because `www.di.ens.fr/~lelarge` is apparently @mlelarge 's personal website's storage on a university's web host which probably cannot handle the bandwidth for all amateur data scientists relying on `torch.dataset`. We should download the original from LeCun's site manually by ourselves, upload to a personal cloud storage that supports http, then use `wget`.

**Comment by EricPengShuai** [comment] 2021-08-04 11:10
> @BernardoOlisan @ChengguiSun the solution from @mlelarge works great, the following worked for me in a notebook
> 
> ```python
> !wget www.di.ens.fr/~lelarge/MNIST.tar.gz
> !tar -zxvf MNIST.tar.gz
> 
> from torchvision.datasets import MNIST
> from torchvision import transforms
> 
> mnist_train = MNIST('./', download=False,
>                     transform=transforms.Compose([
>                         transforms.ToTensor(),
>                     ]), train=True)
> ```

@alisterburt  I encountered the following problems after trying
```python

tar: Error opening archive: Failed to open 'MNIST.tar.gz'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-48b8be9a8697> in <module>
      8                     transform=transforms.Compose([
      9                         transforms.ToTensor(),
---> 10                     ]), train=True)

c:\users\peng\anaconda3\envs\pytorch_1.8\lib\site-packages\torchvision\datasets\mnist.py in __init__(self, root, train, transform, target_transform, download)
     80
     81         if not self._check_exists():
---> 82             raise RuntimeError('Dataset not found.' +
     83                                ' You can use download=True to download it')
     84

RuntimeError: Dataset not found. You can use download=True to download it
```

**Comment by rodrsilv-stark** [comment] 2021-08-04 11:30
Have you tried to decompress the file first?

**Comment by EricPengShuai** [comment] 2021-08-04 11:36
> Have you tried to decompress the file first?

No, I just try it in the ipython(anaconda/pytorch 1.8) in my windows. But I try it in my macbook successfully. I don't know why.

**Comment by SiddhantSadangi** [comment] 2024-05-14 15:27
Is anyone else facing the same issue again?

**Comment by dandv** [comment] 2024-05-23 20:30
Still getting this error with torchvision==0.16.2.

```py
trainset = torchvision.datasets.MNIST(
    "./downloads/mnist",
    download=True,
    train=True,
    transform=transform,
)
```

```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Failed to download (trying next):
HTTP Error 403: Forbidden
```

**Comment by mahtin** [comment] 2024-07-01 06:53
This is still happening intermittently when reading the files from `http://yann.lecun.com/exdb/mnist/` however, this simple fix solves the intermittent nature of this issue.
```diff
< datasets_url = 'http://yann.lecun.com/exdb/mnist/'
> datasets_url = 'https://storage.googleapis.com/cvdf-datasets/mnist/'
```
The same files are present there and in fact many places, for example: https://github.com/golbin/TensorFlow-MNIST/raw/master/mnist/data/ plus other places.

I think it's a sad case of the original site being either overrun or broken.

**Comment by vanjy-eng** [comment] 2024-08-09 03:25
Still seeing this issue on Mac OS.
torch==2.0.1
torchvision==0.15.2

None of the above mentioned methods worked.

Code:

```python
train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST('./data', train=False, transform=transform)
```

Fixed using this stackoverflow issue:
[SSL issue](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org)

**Comment by rudrOwO** [comment] 2024-10-05 08:24
Yes, finding it impossible to bypass the 403 error. I've tried using aforementioned custom headers, but no luck

**Comment by fedhere** [comment] 2024-10-06 15:34
I can bypass the 403 error on colab, but hit a HTTPError 302, which as I understand means I am getting redirected but the redirect fails, which may be dues still to cookies not being set correctly

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

from torchvision import datasets
import torchvision.transforms as transforms
import urllib

num_workers = 0
batch_size = 20
basepath = '.'
transform = transforms.ToTensor()

def set_header_for(url, filename):
    opener = urllib.request.URLopener()
    opener.addheader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36')
    opener.retrieve(
    url, f'{basepath}/{filename}')

set_header_for('http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'train-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz', 'train-labels-idx1-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz', 't10k-images-idx3-ubyte.gz')
set_header_for('http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz', 't10k-labels-idx1-ubyte.gz')
train_data = datasets.MNIST(root='data', train=True,
                                   download=True, transform=transform)
test_data = datasets.MNIST(root='data', train=False,
                                  download=False, transform=transform)
                                  
 --------------------------------------------------------
 
 <ipython-input-11-7b9c22e51c89>:19: DeprecationWarning: URLopener style of invoking requests is deprecated. Use newer urlopen functions/methods
  set_header_for('http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'train-images-idx3-ubyte.gz')
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-11-7b9c22e51c89>](https://localhost:8080/#) in <cell line: 19>()
     17     url, f'{basepath}/{filename}')
     18 
---> 19 set_header_for('http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'train-images-idx3-ubyte.gz')
     20 set_header_for('http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz', 'train-labels-idx1-ubyte.gz')
     21 set_header_for('http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz', 't10k-images-idx3-ubyte.gz')

6 frames
[<ipython-input-11-7b9c22e51c89>](https://localhost:8080/#) in set_header_for(url, filename)
     14     opener = urllib.request.URLopener()
     15     opener.addheader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36')
---> 16     opener.retrieve(
     17     url, f'{basepath}/{filename}')
     18 

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in retrieve(self, url, filename, reporthook, data)
   1819             except OSError:
   1820                 pass
-> 1821         fp = self.open(url, data)
   1822         try:
   1823             headers = fp.info()

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in open(self, fullurl, data)
   1785         try:
   1786             if data is None:
-> 1787                 return getattr(self, name)(url)
   1788             else:
   1789                 return getattr(self, name)(url, data)

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in open_http(self, url, data)
   1963     def open_http(self, url, data=None):
   1964         """Use HTTP protocol."""
-> 1965         return self._open_generic_http(http.client.HTTPConnection, url, data)
   1966 
   1967     def http_error(self, url, fp, errcode, errmsg, headers, data=None):

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in _open_generic_http(self, connection_factory, url, data)
   1957                               response.status)
   1958         else:
-> 1959             return self.http_error(
   1960                 url, response.fp,
   1961                 response.status, response.reason, response.msg, data)

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error(self, url, fp, errcode, errmsg, headers, data)
   1979                 result = method(url, fp, errcode, errmsg, headers, data)
   1980             if result: return result
-> 1981         return self.http_error_default(url, fp, errcode, errmsg, headers)
   1982 
   1983     def http_error_default(self, url, fp, errcode, errmsg, headers):

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error_default(self, url, fp, errcode, errmsg, headers)
   1984         """Default error handler: close the connection and raise OSError."""
   1985         fp.close()
-> 1986         raise HTTPError(url, errcode, errmsg, headers, None)
   1987 
   1988     if _have_ssl:

HTTPError: HTTP Error 302: Found
```
