### ISSUE TITLE
wrap_dataset_for_transforms_v2 with transforms not working as intended

### ISSUE THREAD

**Issue by liopeer** [pytorch/vision#8720] opened 2024-11-11 12:54 UTC
### 🐛 Describe the bug

When using the `wrap_dataset_for_transforms_v2` wrapper for `torchvision.datasets` classes it seems that the `transform` being passed during instantiation of the dataset is not utilized properly. The issue was observed the `VOCDetection` dataset:
- when using `RandomCrop`, passing it to `VOCDetection` and wrapping it by `wrap_dataset_for_transforms_v2`, the image gets cropped, but the bounding boxes are unaffected (image in the middle)
- when not passing any transform, but instead applying the transform manually outside of the wrapped dataset, it works as intended (image on the right)
- image on the left is the original without cropping

![v2_issue](https://github.com/user-attachments/assets/9d9ec95b-e66c-4412-98e4-cc8352d8a4dc)

Code to reproduce:
```python
from random import Random
from torchvision.datasets import (
    wrap_dataset_for_transforms_v2,
    CocoDetection,
    VOCDetection,
    Cityscapes
)
from torchvision.transforms import ToTensor
from torchvision.transforms.v2 import Compose, RandomCrop, ToImage, ToDtype
import torch
import matplotlib.pyplot as plt
from torchvision.utils import draw_bounding_boxes

transform1 = ToTensor()
transform2 = Compose([ToImage(), ToDtype(torch.float32, scale=True), RandomCrop((360, 360))])
ds1 = wrap_dataset_for_transforms_v2(VOCDetection("./voc", transform=transform1, download=True))
ds2 = wrap_dataset_for_transforms_v2(VOCDetection("./voc", transform=transform2))
ds3 = wrap_dataset_for_transforms_v2(VOCDetection("./voc"))

fig, ax = plt.subplots(1, 3)

# plot original
sample1 = ds1[0]
img1 = sample1[0]
boxes1 = sample1[1]["boxes"]
img1_w_boxes = draw_bounding_boxes(img1, boxes1, width=3, colors="green")
ax[0].imshow(img1_w_boxes.permute(1,2,0))

# plot wrongly transformed boxes
sample2 = ds2[0]
img2 = sample2[0]
boxes2 = sample2[1]["boxes"]
img2_w_boxes = draw_bounding_boxes(img2, boxes2, width=4, colors="green")
ax[1].imshow(img2_w_boxes.permute(1,2,0))

# properly transform manually
sample3 = ds3[0]
img3 = sample3[0]
boxes3 = sample3[1]["boxes"]
img3, boxes3 = transform2(img3, boxes3) # manual transform
img3_w_boxes = draw_bounding_boxes(img3, boxes3, width=3, colors="green")
ax[2].imshow(img3_w_boxes.permute(1,2,0))

fig.show()
```

### Versions

```bash
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] (64-bit runtime)
Python platform: macOS-15.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.4.0
[pip3] torch==2.5.1
[pip3] torchmetrics==1.5.1
[pip3] torchvision==0.20.1
[conda] Could not collect
```

**Comment by NicolasHug** [comment] 2024-11-28 13:52
Hi @liopeer , thanks for the report.

It took me a while to understand what's going on: the issue is with the `transform` parameter. It should be `transforms`.

The `transform` parameter can only transform the input image, it cannot transform the target (where the bounding boxes are).

I would agree it may be a bit surprising, but these 2 parameters were introduced long-before the v2 transform and `wrap_dataset_for_transforms_v2`. One way to look at it is that even before the introduction of the v2 transforms, using `transform=...` would *not* enable you to transform the bounding boxes. So, it's a bit surprising, but I'm not sure we could have gone for something different here.

**Comment by NicolasHug** [comment] 2024-11-29 10:33
I think the original problem was addressed, so I'll close it. LMK if you think there's anything we could clarify within the docs @liopeer!

**Closed by NicolasHug** 2024-11-29 10:33 UTC

**Comment by liopeer** [comment] 2024-12-23 09:16
For anyone coming across this: The only thing to make above example work is to change the following line
```python
ds1 = wrap_dataset_for_transforms_v2(VOCDetection("./voc", transform=transform1, download=True))
```
to
```python
ds1 = wrap_dataset_for_transforms_v2(VOCDetection("./voc", transforms=transform1, download=True))
```
