### ISSUE TITLE
Train FasterRCNN with negative samples

### ISSUE THREAD

**Issue by LogicNg** [pytorch/vision#4189] opened 2021-07-17 10:47 UTC
According to [this](https://github.com/pytorch/vision/releases/tag/v0.6.0) release note, FasterRCNN supports negative samples, but you have to set `target` for any negative samples as follow:

```python
target = {"boxes": torch.zeros((0, 4), dtype=torch.float32),
          "labels": torch.zeros(0, dtype=torch.int64),
          "image_id": 4,
          "area": torch.zeros(0, dtype=torch.float32),
          "masks": torch.zeros((0, image_height, image_width), dtype=torch.uint8),
          "keypoints": torch.zeros((17, 0, 3), dtype=torch.float32),
          "iscrowd": torch.zeros((0,), dtype=torch.int64)}
```

I did the same. Then I use the [`train_one_epoch`](https://github.com/pytorch/vision/blob/master/references/detection/engine.py) function to start training. I got the following error.

```python
Loss is nan, stopping training

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-22-faf337932278> in <module>
     11 
     12 for epoch in range(num_epochs):
---> 13     train_one_epoch(model, optimizer, train_data_loader, device, epoch, print_freq=10)
     14     lr_scheduler.step()
     15     evaluate(model, valid_data_loader, device=device)

/kaggle/working/engine.py in train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq)
     41             print("Loss is {}, stopping training".format(loss_value))
     42             print(loss_dict_reduced)
---> 43             sys.exit(1)
     44 
     45         optimizer.zero_grad()

SystemExit: 1
```

Any idea what is going on?

**Comment by datumbox** [comment] 2021-08-17 17:11
This seems duplicate of #4147. I would recommend following the other issue to keep things tidy. :)

**Closed by datumbox** 2021-08-17 17:11 UTC
Labels: topic: object detection
