### ISSUE TITLE
Can't load multiple classes in LSUN dataset

### ISSUE THREAD

**Issue by MaverickMeerkat** [pytorch/vision#2611] opened 2020-08-24 14:40 UTC
`LSUN_data = LSUN("path", classes=["bedroom_val", "classroom_val"], transform=tf)`

Raises the following error:

> ValueError                                Traceback (most recent call last)
> ~\Anaconda3\envs\hw1_env\lib\site-packages\torchvision\datasets\lsun.py in _verify_classes(self, classes)
>      99         try:
> --> 100             verify_str_arg(classes, "classes", dset_opts)
>     101             if classes == 'test':
> 
> ~\Anaconda3\envs\hw1_env\lib\site-packages\torchvision\datasets\utils.py in verify_str_arg(value, arg, valid_values, custom_msg)
>     265         msg = msg.format(type=type(value), arg=arg)
> --> 266         raise ValueError(msg)
>     267 
> 
> ValueError: Expected type str for argument classes, but got type <class 'list'>.
> 
> During handling of the above exception, another exception occurred:

> IndexError                                Traceback (most recent call last)
> <ipython-input-11-8c315ff6339e> in <module>
> ----> 1 LSUN_data = LSUN("C:\\Work\\TAU\\1st semester\\CNN\\Final Project\\lsun-master", classes=["bedroom_val", "classroom_val"], transform=tf)
> 
> ~\Anaconda3\envs\hw1_env\lib\site-packages\torchvision\datasets\lsun.py in __init__(self, root, classes, transform, target_transform)
>      74         super(LSUN, self).__init__(root, transform=transform,
>      75                                    target_transform=target_transform)
> ---> 76         self.classes = self._verify_classes(classes)
>      77 
>      78         # for each class, create an LSUNClassDataset
> 
> ~\Anaconda3\envs\hw1_env\lib\site-packages\torchvision\datasets\lsun.py in _verify_classes(self, classes)
>     113                           "but got type {}.")
>     114             for c in classes:
> --> 115                 verify_str_arg(c, custom_msg=msg_fmtstr.format(type(c)))
>     116                 c_short = c.split('_')
>     117                 category, dset_opt = '_'.join(c_short[:-1]), c_short[-1]
> 
> IndexError: tuple index out of range

 - PyTorch / torchvision Version '1.3.0'
 - OS (e.g., Linux): Windows
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): Conda
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.1

**Comment by pmeier** [comment] 2020-08-24 15:02
Hi @MaverickMeerkat, I can't reproduce this with `torchvision==0.7.0`. Since `torchvision==0.4.1` (corresponds to `torch==1.3.0`) no changes happened that should cause this. If the line you posted above is indeed enough to reproduce the error for you, could please post your `torch` and `torchvision` versions? You can do so by

```python
import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)
```

**Comment by MaverickMeerkat** [comment] 2020-08-24 16:57
This is the minimal code: 

```
import torch
from torchvision.datasets import LSUN

LSUN_data = LSUN("C:\\Work\\TAU\\1st semester\\CNN\\Final Project\\lsun-master", classes=["bedroom_val", "classroom_val"])
```

torch 1.3.0
torchvision 0.4.1

**Comment by pmeier** [comment] 2020-08-24 17:42
Can confirm, bug is also present in `torchvision==0.7.0`. It was introduced in 59c97d7. It happens because `msg_fmtstr` is overwritten inside the loop body 

https://github.com/pytorch/vision/blob/78ed10cc51067f1a6bac9352831ef37a3f842784/torchvision/datasets/lsun.py#L106-L119

The second time it reaches L109, the format fails since it expects three values. 

---

Incidentally, this was fixed in ea6b879. As such, I'm closing this.

---

@MaverickMeerkat To solve this you need to install the current nightly version of `torch` / `torchvision`.

**Closed by pmeier** 2020-08-24 17:42 UTC
Labels: awaiting response, bug, module: datasets, needs reproduction

**Comment by pmeier** [comment] 2020-08-25 08:13
@MaverickMeerkat If you are bound to a stable version you can monkeypatch the buggy code, since it is only checking the validity of the input arguments:

```python
from torchvision.datasets import LSUN

LSUN._verify_classes = lambda self, classes: list(classes)
LSUN_data = LSUN("path", classes=["bedroom_val", "classroom_val"])
```

**Comment by MaverickMeerkat** [comment] 2020-08-25 10:19
Its ok.
Thanks for your help!
