### ISSUE TITLE
Inception class in GoogLeNet,wrong kernel size?

### ISSUE THREAD

**Issue by mattiaguerri** [pytorch/vision#1171] opened 2019-07-25 15:19 UTC
In the GoogLeNet implementatoin, the inception class, in branch3 the kernel size of the second convolution is 3. Shouldn’t that be 5?

**Comment by TheCodez** [comment] 2019-07-25 18:59
https://github.com/pytorch/vision/issues/906#issuecomment-493748030

**Comment by TheCodez** [comment] 2019-07-25 19:05
@fmassa we should probably add a comment to the affected line as it seems to often lead to confusion.

**Comment by fmassa** [comment] 2019-07-26 08:45
@TheCodez could you send a PR adding the comment?

**Comment by fmassa** [comment] 2019-07-26 08:46
Closing as a duplicate of https://github.com/pytorch/vision/issues/906#issuecomment-493748030
Let's keep the discussion there

**Closed by fmassa** 2019-07-26 08:46 UTC
Labels: duplicate, module: models
