### ISSUE TITLE
torch.ops.video_reader.probe_video_from_memory(video_data) 

### ISSUE THREAD

**Issue by DaBaiTuu** [pytorch/vision#7971] opened 2023-09-18 10:46 UTC
### 🐛 Describe the bug

'_OpNamespace' 'video_reader' object has no attribute 'probe_video_from_memory'

when i run and look into ` torchvision.io._probe_video_from_memory(video_tensor)` and look into the function in torchvision 

i found  `torch.ops.video_reader.probe_video_from_memory(video_data)` in function defined in torchvision and it is not reachable 

the when i run it i got the error '_OpNamespace' 'video_reader' object has no attribute 'probe_video_from_memory'

### Versions

torch                         2.0.0
torch-scatter                 2.1.1+pt20cu117
torchinfo                     1.8.0
torchmetrics                  0.11.4
torchvision                   0.15.1

**Comment by malfet** [comment] 2023-09-18 23:38
Moving to torchvision, but I guess it will get "needs reproduction" label as details shared on the issue are somewhat insufficient. What OS do you using and what sample code/app returns this error?

**Comment by DaBaiTuu** [comment] 2023-09-19 01:55
> Moving to torchvision, but I guess it will get "needs reproduction" label as details shared on the issue are somewhat insufficient. What OS do you using and what sample code/app returns this error?

ubuntu 18.04 when i try to run the facebookresearch's code : mae_st with 
@Article{MaskedAutoencodersSpatiotemporal2022,
  author  = {Christoph Feichtenhofer and Haoqi Fan and Yanghao Li and Kaiming He},
  journal = {arXiv:2205.09113},
  title   = {Masked Autoencoders As Spatiotemporal Learners},
  year    = {2022},
}

you can find the source code here: https://github.com/facebookresearch/mae_st
and the code script is located in utils.decoder.decode ,line 118, :`meta = io._probe_video_from_memory(video_tensor)`

**Comment by pmeier** [comment] 2023-09-19 07:38
From our [public / private policy](https://github.com/pytorch/vision/blob/main/maintainer_guide.md#what-is-public-and-what-is-private):

> - modules that can be accessed without leading underscore are public
> - **objects in a public file that don't have a leading underscore are public**
> - class attributes are public iff they have no leading underscore
> - the **rest of the** modules / **objects** / class attributes **are considered private**

(emphasis mine)

Meaning, `torchvision.io._probe_video_from_memory` is a private utility for which we don't provide any BC guarantees.

**Comment by pmeier** [comment] 2023-09-19 08:08
As for the actual issue here: you likely have installed `torchvision` from PyPI or conda, correct? If so, these binaries do *not* contain the video backend due to licensing issues. If you want that, [compile from source](https://github.com/pytorch/vision#unstable-video-backend).

**Comment by DaBaiTuu** [comment] 2023-09-19 08:44
Yes,I have installed torchvision via PyPI.
What i want to do is to reproduce the project i mentioned above, So it means the `mae_st` use the private utility and compile the video backend by themselves, and it's hard for me to reproduce unless i choose pyav backend or complie from source?

**Comment by pmeier** [comment] 2023-09-19 08:52
Correct. The link the install instructions from the original repository and in there you can find this old thread facebookresearch/SlowFast#181 that deals with this exact issue.

Closing this, since it is not a `torchvision` issue.

**Closed by pmeier** 2023-09-19 08:52 UTC
Labels: module: video
