### ISSUE TITLE
make_grid broken with mps device Tensors, whole grid is the 'first' image

### ISSUE THREAD

**Issue by Vargol** [pytorch/vision#6533] opened 2022-09-01 20:22 UTC
### 🐛 Describe the bug

When calling make_grid on Tensor and List of Tensors where the device in 'mps'  it returns a grid where all the Tensors are the same.

Simple example
create a venv and activate
cd into the venv directory
install the nightlies
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu

unzip the attached zip file, it contains a python script and two images.
validate the python script and run it.

```
from PIL import Image
from torchvision.utils import make_grid
import torchvision.transforms as transforms
import torch
 

img1 = Image.open('00035.png')
img2 = Image.open('00036.png')

transform = transforms.Compose([
    transforms.PILToTensor()
])


t_img1 = transform(img1).to(torch.device("mps"), dtype=torch.float32)  / 256.0
t_img2 = transform(img2).to(torch.device("mps"), dtype=torch.float32)  / 256.0

grid = make_grid([t_img1, t_img2], nrow=1)

gridImage =  transforms.ToPILImage()(grid.cpu());

gridImage.save('mps_grid.png')

t_img1 = transform(img1).to(torch.device("cpu"), dtype=torch.float32)  / 256.0
t_img2 = transform(img2).to(torch.device("cpu"), dtype=torch.float32)  / 256.0

grid = make_grid([t_img1, t_img2], nrow=1)

gridImage =  transforms.ToPILImage()(grid.cpu());

gridImage.save('cpu_grid.png')
```

It generate two images, you'll see the cpu_grid image are the two images vertically stacked, the mps_grid image has the same image vertically stacked twice.

[make_grid_bug.zip](https://github.com/pytorch/vision/files/9473078/make_grid_bug.zip)

### Versions

PyTorch version: 1.13.0.dev20220901
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.4
Libc version: N/A

Python version: 3.10.4 (main, May 10 2022, 03:52:14) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-12.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.13.0.dev20220901
[pip3] torchaudio==0.13.0.dev20220901
[pip3] torchvision==0.14.0.dev20220901
[conda] Could not collect

**Comment by datumbox** [comment] 2022-09-04 08:21
@Vargol Thanks for reporting. 

There might be an issue on one of the mps kernels that `make_grid()` uses. Looking at the [code](https://github.com/pytorch/vision/blob/main/torchvision/utils.py#L24) of the method I see the following PyTorch core methods being invoked:
- torch.stack()
- tensor.unsqueeze()
- tensor.new_full()
- tensor.narrow() followed by a tensor.copy_()

Unfortunately I don't have the hardware to reproduce myself and I think we should raise the problem to the PyTorch Core devs. Currently there is a minor issue with the code you provide to reproduce the issue (possibly due to copy-pasting), could you please correct it? Moreover it would help if you add an assertion to show-case that the result is not the expected along with any the actual output of the script vs the expected. Normally I would be happy to fill this details for you before escalating but I don't have the hardware to reproduce. Thanks in a advance.

**Comment by Vargol** [comment] 2022-09-04 09:10
I've edited the code, but it will be a while before I can test the edit is right, looks like a reference to the zip file split a line in half.

**Comment by datumbox** [comment] 2022-09-04 09:14
@Vargol Could you also clarify if the issue appears with any image or there seems to be something specific about those you picked up from the zip?

**Comment by Vargol** [comment] 2022-09-04 09:22
I'll have to do more testing, but it should be a generic issue, I can't see why those images would be special, apart from being square.
I came across the bug in the mps forks of the stable diffsion scripts that are really popular at the moment, it occurs for every grid image created in those, although some forks have merged a work around of moving the tensors holding the images images to the CPU before making the grid image

**Comment by Vargol** [comment] 2022-09-04 09:59
Apologies is this comment is a dupe but I'm sure I sent it, but a revisit to the page shows no sign of it.

I've snuck on the M1 Mac Mini I've run a quick test with a couple of non-square random images and the same issue occurs.
Checked with and without alpha  and a mix or png and jpeg and all do the same

**Comment by Vargol** [comment] 2022-09-04 10:39
Updated code with an assert

```
from PIL import Image
from torchvision.utils import make_grid
import torchvision.transforms as transforms
import torch


img1 = Image.open('00035.png')
img2 = Image.open('00036.png')

transform = transforms.Compose([
    transforms.PILToTensor()
])


t_img1 = transform(img1).to(torch.device("mps"), dtype=torch.float32)  / 256.0
t_img2 = transform(img2).to(torch.device("mps"), dtype=torch.float32)  / 256.0

grid = make_grid([t_img1, t_img2], nrow=1)

gridImageMPS =  transforms.ToPILImage()(grid.cpu());

gridImageMPS.save('mps_grid.png')


t_img1 = transform(img1).to(torch.device("cpu"), dtype=torch.float32)  / 256.0
t_img2 = transform(img2).to(torch.device("cpu"), dtype=torch.float32)  / 256.0

grid = make_grid([t_img1, t_img2], nrow=1)

gridImage =  transforms.ToPILImage()(grid.cpu());

gridImage.save('cpu_grid.png')

assert  list(gridImageMPS.getdata()) == list(gridImage.getdata()), 'the images  are different'

```

**Comment by Vargol** [comment] 2022-09-04 10:40
raised
https://github.com/pytorch/pytorch/issues/84523

**Comment by datumbox** [comment] 2022-09-04 13:25
Thanks for raising it at PyTorch Core. I believe the issue is there so I'll close this issue to avoid duplicates. I'll keep an eye on the other issue but if it turns out the problem is on TorchVision's end, feel free to reopen.

**Closed by datumbox** 2022-09-04 13:25 UTC

**Comment by AmirMardan** [comment] 2023-01-04 01:59
The same problem comes up while using `torchvision.utils.save_image`. It saves just the first tensor in the batch for all batches.
