### ISSUE TITLE
Attempted relative import with no known parent package

### ISSUE THREAD

**Issue by sharjeelanjum** [pytorch/vision#4129] opened 2021-06-28 07:59 UTC
Hello, I have cloned the repository on my system to run the resnet.py file to check the results on CIFAR10 dataset (by default) that is used in the ADDITIVE POWERS-OF-TWO QUANTIZATION: AN EFFICIENT NON-UNIFORM DISCRETIZATION FOR NEURAL NETWORKS published paper but it shows an "error internally_replaced_utils import load_state_dict_from_url
ImportError: attempted relative import with no known parent package."
Could you please guide me.
Thanks in Advance

**Comment by NicolasHug** [comment] 2021-06-28 08:16
Hi @sharjeelanjum , could you please provide a minimal reproducible example with the full stack trace please?

**Comment by sharjeelanjum** [comment] 2021-06-28 08:23
> Hi @sharjeelanjum , could you please provide a minimal reproducible example with the full stack trace please?

Thanks for your quick response, actually I am, following this published paper https://arxiv.org/abs/1909.13144 , and the professor ordered me to run this model to compare the results with the results of the authors mentioned in this paper. According to the read file of the github repository, set all the requirements but getting an error which can be seen in the following screenshot when try to run resnet.py file
![github err](https://user-images.githubusercontent.com/57236662/123604197-96373980-d835-11eb-84bc-b65f5c83fdcc.JPG)

**Comment by NicolasHug** [comment] 2021-06-28 08:36
it looks like you copy/pasted the resnet.py file out of the torchvision package into another folder?

**Comment by sharjeelanjum** [comment] 2021-06-28 08:42
yes it looks likes that, but actually, I did not change anything just cloned the GitHub repository, run the setup.py file after installing torch and then went in the model's folder and run the file. sorry for the silly explanation. (New student)

**Comment by NicolasHug** [comment] 2021-06-28 08:51
oh, I see.

what are you trying to achieve exactlty?

Because https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py is just a file that defines classes and function, but it doesn't run anything.

If you want to use stuff from this file, you should create a completely separate file, outside of the torchvision directory, install torhvision, and then you can import stuff e.g.

```py
from torchvision.models import resnet50
my_model = resnet50(pretrained=True)
```

**Comment by sharjeelanjum** [comment] 2021-06-28 08:56
oh, I got it, you mean I have to create another python file and load this model and perform inference. right?
Here is the main task I want to perform:



Assignment:
1.	Please read the attached paper “Additive Powers-of-Two Quantization: An Efficient Non-uniform Discretization for Neural Networks” in detail. Understand the idea behind this quantization method and study the code provided by the authors in github.
2.	Setup the training and verify the results of this paper, using the code provided by the authors in github. Check if you are able to reproduce the results. Only do this for Cifar10 dataset, as the ImageNet training takes very long time.
3.	Apply this technique (Additive powers of two, APoT) to MobileNetV2 and check the following:
a.	Is APoT able to reduce the training / inference time in MobileNetV2?
b.	Is the accuracy dropped drastically?

**Comment by NicolasHug** [comment] 2021-06-28 09:00
> oh, I got it, you mean I have to create another python file and load this model and perform inference. right?

Yes

Since this isn't a torchvision-related issue, I'll close this one if you don't mind.

As a good starting point regarding creating the files etc, you can look e.g. at https://github.com/pytorch/vision/blob/master/references/classification/train.py

**Closed by NicolasHug** 2021-06-28 09:00 UTC

**Comment by sharjeelanjum** [comment] 2021-06-28 09:05
Thanks for your cooperation
