### ISSUE TITLE
Bad zipfile error while downloading CelebA dataset

### ISSUE THREAD

**Issue by square-1111** [pytorch/vision#2756] opened 2020-10-05 12:00 UTC
## 🐛 Bug

I am working with CelebA dataset with `download = True`. I am getting an error 
```BadZipFile: File is not a zip file```

## To Reproduce  
```
import torchvision.datasets as dset
data = dset.celeba.CelebA(root='.', split='train', target_type='attr', transform=None, download=True)
```

## Environment
I am working on Google Colab
```
PyTorch version: 1.6.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A  

Versions of relevant libraries:
[pip3] numpy==1.18.5 
[pip3] torch==1.6.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect```

cc @pmeier

**Comment by fmassa** [comment] 2020-10-05 12:19
This is a duplicate of https://github.com/pytorch/vision/issues/2387 and https://github.com/pytorch/vision/issues/2317, and a "fix" is done in https://github.com/pytorch/vision/pull/2321

The issue is that CelebA is stored in Google Drive, and it has exceeded the download quota for the day.
Try again in a different moment and it should work

**Closed by fmassa** 2020-10-05 12:19 UTC
Labels: module: datasets

**Comment by square-1111** [comment] 2020-10-06 10:42
Thank You for the leads.

**Comment by square-1111** [comment] 2020-10-08 09:00
`AttributeError: 'tqdm' object has no attribute 'close'` -- I am getting this error on local machine. Is this error associated with exceeding download quota or something else?

**Comment by vfdev-5** [comment] 2020-10-08 09:02
@square-1111 could you please provide a minimal code snippet and list of installed packages to reproduce the issue. Thanks

**Comment by fmassa** [comment] 2020-10-08 09:03
This error is different -- can you check if you have tqdm installed? If not, might be that the helper implementation of tqdm that we provide doesn't have the close method

**Comment by square-1111** [comment] 2020-10-08 09:44
@vfdev-5 I am trying to run
```import torchvision.datasets as dset
img_path ='.'
data = dset.celeba.CelebA(root=img_path, split='train', target_type='attr', transform=None, download=True)
```

and getting this error `AttributeError: 'tqdm' object has no attribute 'close'`

**Comment by fmassa** [comment] 2020-10-08 13:33
@square-1111 can you try doing in a new interpreter
```python
import tqdm
```
and report back? You probably don't have tqdm installed, and the [PyTorch fallback doesn't implement `close`](https://github.com/pytorch/pytorch/blob/acca11b89808c8d57e914057a6c0e60cb66cea46/torch/hub.py#L22-L49)

@pmeier we should probably fix this somehow, either by removing the need of a `close` in our offending function or by adding a `close` to the fallback implementation in PyTorch

**Comment by pmeier** [comment] 2020-10-08 13:35
I'll look into it.

**Comment by pmeier** [comment] 2020-10-08 17:27
pytorch/pytorch#46040 will fix the `tqdm` mock.
