### ISSUE TITLE
Bug: Import fails because PILLOW_VERSION no longer exists

### ISSUE THREAD

**Issue by fritzo** [pytorch/vision#1726] opened 2020-01-08 00:40 UTC
`PIL.PILLOW_VERSION` appears to have been removed in Pillow 7.

Traceback:
```
Traceback (most recent call last):
  File "examples/vae.py", line 9, in <module>
    from torchvision import datasets, transforms
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'
```
Pip freeze

<details>

```
$ pip freeze
apipkg==1.5
atomicwrites==1.2.1
attrs==18.2.0
certifi==2018.10.15
entrypoints==0.3
execnet==1.7.1
flake8==3.7.9
funsor==0.1.2
mccabe==0.6.1
mock==2.0.0
more-itertools==4.3.0
multipledispatch==0.6.0
nose==1.3.7
numpy==1.16.2
opt-einsum==3.1.0
pandas==0.25.3
pbr==5.0.0
Pillow==7.0.0
Pillow-SIMD==6.0.0.post0
pipenv==2018.11.26
pluggy==0.8.0
py==1.7.0
pycodestyle==2.5.0
pyflakes==2.1.1
pyro-api==0.1.1
pyro-ppl==1.1.0
pytest==4.3.1
pytest-forked==1.1.3
pytest-xdist==1.27.0
python-dateutil==2.8.1
pytz==2019.3
six==1.11.0
torch==1.3.0+cpu
torchvision==0.4.2
tqdm==4.41.1
virtualenv==16.0.0
virtualenv-clone==0.4.0
```

</details>

**Comment by cl2227619761** [comment] 2020-01-08 01:55
use pillow==0.6.1 is ok

**Comment by fmassa** [comment] 2020-01-08 10:08
Hi,

Thanks for the report.

This is a duplicate of https://github.com/pytorch/vision/issues/1712 which has been fixed in torchvision master / nightly, and the fix will be available in the next stable release next week.

**Closed by fmassa** 2020-01-08 10:08 UTC
