### ISSUE TITLE
`download` parameter of `MNIST()` should be explained at the end

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8781] opened 2024-12-04 19:04 UTC
### 📚 The doc issue

[The doc](https://pytorch.org/vision/stable/generated/torchvision.datasets.MNIST.html) of `MNIST()` says `download` parameter at the end as shown below:

> class torchvision.datasets.MNIST(root: [Union](https://docs.python.org/3/library/typing.html#typing.Union)[[str](https://docs.python.org/3/library/stdtypes.html#str), [Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path)], train: [bool](https://docs.python.org/3/library/functions.html#bool) = True, transform: [Optional](https://docs.python.org/3/library/typing.html#typing.Optional)[[Callable](https://docs.python.org/3/library/typing.html#typing.Callable)] = None, target_transform: [Optional](https://docs.python.org/3/library/typing.html#typing.Optional)[[Callable](https://docs.python.org/3/library/typing.html#typing.Callable)] = None, download: [bool](https://docs.python.org/3/library/functions.html#bool) = False)

But `download` parameter is explained in the middle as shown below:

> Parameters:
> - root (str or pathlib.Path) – Root directory of dataset where MNIST/raw/train-images-idx3-ubyte and MNIST/raw/t10k-images-idx3-ubyte exist.
> - train ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – If True, creates dataset from train-images-idx3-ubyte, otherwise from t10k-images-idx3-ubyte.
> - download ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – If True, downloads the dataset from the internet and puts it in root directory. If dataset is already downloaded, it is not downloaded again.
> - transform (callable, optional) – A function/transform that takes in a PIL image and returns a transformed version. E.g, transforms.RandomCrop
> - target_transform (callable, optional) – A function/transform that takes in the target and transforms it.

### Suggest a potential alternative/fix

So `download` parameter should be explained at the end as shown below:

> Parameters:
> - root (str or pathlib.Path) – Root directory of dataset where MNIST/raw/train-images-idx3-ubyte and MNIST/raw/t10k-images-idx3-ubyte exist.
> - train ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – If True, creates dataset from train-images-idx3-ubyte, otherwise from t10k-images-idx3-ubyte.
> - transform (callable, optional) – A function/transform that takes in a PIL image and returns a transformed version. E.g, transforms.RandomCrop
> - target_transform (callable, optional) – A function/transform that takes in the target and transforms it.
> - download ([bool](https://docs.python.org/3/library/functions.html#bool), optional) – If True, downloads the dataset from the internet and puts it in root directory. If dataset is already downloaded, it is not downloaded again.

**Comment by NicolasHug** [comment] 2024-12-05 11:04
Thanks @hyperkai , closing as duplicate of your other issue: https://github.com/pytorch/vision/issues/8780

**Closed by NicolasHug** 2024-12-05 11:04 UTC
