### ISSUE TITLE
Failed to build from source (nvcc compilation errors)

### ISSUE THREAD

**Issue by plammens** [pytorch/vision#1076] opened 2019-07-03 09:24 UTC
On Windows 10, trying to build `torchvision` from latest `master` source (5508815 at time of writing) to solve #1018 .

Using a `conda` environment with the following packages:

```bash
conda list
```

<details>

```text
# packages in environment at C:\Users\Paolo\Anaconda3\envs\torch:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0
backcall                  0.1.0                    py36_0
beautifulsoup4            4.6.3                    py36_0
blas                      1.0                         mkl
bleach                    3.1.0                    py36_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py36_0
cffi                      1.12.3           py36h7a1dbc1_0
chardet                   3.0.4                    py36_1
colorama                  0.4.1                    py36_0
conda                     4.7.5                    py36_0
conda-build               3.18.5                   py36_0
conda-package-handling    1.3.10                   py36_0
cryptography              2.7              py36h7a1dbc1_0
cudatoolkit               10.0.130                      0
cycler                    0.10.0           py36h009560c_0
decorator                 4.4.0                    py36_1
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py36_0
filelock                  3.0.12                     py_0
freetype                  2.9.1                ha9979f8_1
glob2                     0.7                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
intel-openmp              2019.4                      245
ipdb                      0.12                     pypi_0    pypi
ipykernel                 5.1.1            py36h39e3cac_0
ipython                   7.6.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
jedi                      0.10.2           py36hed927a0_0
jinja2                    2.10.1                   py36_0
joblib                    0.13.2                   py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.4                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.5.0                      py_0
kiwisolver                1.1.0            py36ha925a31_0
libarchive                3.3.3                h0643e63_5
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36he774522_0
matplotlib                3.1.0            py36hc8f65d3_0
menuinst                  1.4.16           py36he774522_0
mistune                   0.8.4            py36he774522_0
mkl                       2019.4                      245
mkl-service               2.0.2            py36he774522_0
mkl_fft                   1.0.12           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
mlxtend                   0.16.0                   pypi_0    pypi
msys2-conda-epoch         20160418                      1
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0            py36h3a5bc1b_0
ninja                     1.9.0            py36h74a9793_0
notebook                  5.7.8                    py36_0
numpy                     1.16.4           py36h19fb1c0_0
numpy-base                1.16.4           py36hc3f5095_0
olefile                   0.46                     py36_0
openssl                   1.1.1c               he774522_1
pandas                    0.24.2           py36ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
pbs                       0.110                    pypi_0    pypi
pickleshare               0.7.5                    py36_0
pillow                    6.0.0            py36hdc69c19_0
pip                       19.1.1                   py36_0
pkginfo                   1.5.0.1                  py36_0
plotly                    3.10.0                     py_0
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.9                    py36_0
psutil                    5.6.3            py36he774522_0
py-lief                   0.9.0            py36ha925a31_2
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pygments                  2.4.2                      py_0
pyopenssl                 19.0.0                   py36_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.7.0                    py36_0
python                    3.6.7                h9f7ef89_2
python-dateutil           2.8.0                    py36_0
python-libarchive-c       2.8                      py36_6
pytorch                   1.1.0           py3.6_cuda100_cudnn7_1    pytorch
pytorch-nightly           1.2.0.dev20190702 py3.6_cuda100_cudnn7_0    pytorch
pytz                      2019.1                     py_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.5                 py36_1000
pyyaml                    5.1.1            py36he774522_0
pyzmq                     18.0.0           py36ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.5.1                      py_0
requests                  2.22.0                   py36_0
retrying                  1.3.3                    py36_2
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-learn              0.21.2           py36h6288b17_0
scipy                     1.2.1            py36h29ff71c_0
seaborn                   0.9.0                    pypi_0    pypi
send2trash                1.5.0                    py36_0
setuptools                41.0.1                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.12.0                   py36_0
sqlite                    3.28.0               he774522_0
terminado                 0.8.2                    py36_0
testpath                  0.4.2                    py36_0
tk                        8.6.8                hfa6e2cd_0
torchvision               0.3.0              py36_cu100_1    pytorch
tornado                   4.5.3                    py36_0
tqdm                      4.32.1                     py_0
traitlets                 4.3.2            py36h096827d_0
urllib3                   1.24.2                   py36_0
vc                        14.1                 h21ff451_1    peterjc123
vs2015_runtime            14.15.26706          h3a45250_4
vs2017_runtime            15.4.27004.2010               1    peterjc123
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
wheel                     0.33.4                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

</details>

## Steps to reproduce

```bash
git clone https://github.com/pytorch/vision.git
cd vision
python setup.py clean
python setup.py install
```

## Result

At one of the executions of `nvcc.exe`,

<details>

```text
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe -c C:\Users\Paolo\Downloads\vision\torchvision\csrc\cuda\nms_cuda.cu -o build\temp.win-amd64-3.6\Release\Users\Paolo\Downloads\vision\torchvision\csrc\cuda\nms_cuda.obj -Xcompiler /wd4819 -Xcompiler /MD -IC:\Users\Paolo\Downloads\vision\torchvision\csrc -IC:\Users\Paolo\Anaconda3\envs\torch\lib\site-packages\torch\include -IC:\Users\Paolo\Anaconda3\envs\torch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Paolo\Anaconda3\envs\torch\lib\site-packages\torch\include\TH -IC:\Users\Paolo\Anaconda3\envs\torch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\Paolo\Anaconda3\envs\torch\include -IC:\Users\Paolo\Anaconda3\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
nms_cuda.cu
```
</details>

 I get the following compilation errors:

<details>

```text
 C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(203): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: c10::Half < c10::Half

C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(204): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: c10::Half <= c10::Half

C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(205): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: c10::Half > c10::Half

C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(206): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: c10::Half >= c10::Half

C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(207): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half

C:/Users/Paolo/Anaconda3/envs/torch/lib/site-packages/torch/include\THC/THCNumerics.cuh(209): error: more than one operator "!=" matches these operands:
            built-in operator "arithmetic != arithmetic"
            function "operator!=(const __half &, const __half &)"
            operand types are: c10::Half != c10::Half

6 errors detected in the compilation of "C:/Users/Paolo/AppData/Local/Temp/tmpxft_000018bc_00000000-8_nms_cuda.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2
```

</details>

**Comment by peterjc123** [comment] 2019-07-03 09:40
Duplicate of https://github.com/pytorch/vision/issues/1029.

**Closed** 2019-07-03 09:46 UTC

**Comment by fmassa** [comment] 2019-07-03 10:03
@peterjc123 is there something we can do in torchvision to improve the experience?

Like, do we need to improve the documentation or the build scripts?

**Comment by peterjc123** [comment] 2019-07-03 10:32
@fmassa Looks like we should fix the build steps for CUDA builds. That is to add `export NVCC_FLAGS=-D__CUDA_NO_HALF_OPERATORS__` into the `Build from source` section.

**Comment by plammens** [comment] 2019-07-03 10:46
> @fmassa Looks like we should fix the build steps for CUDA builds. That is to add `export NVCC_FLAGS=-D__CUDA_NO_HALF_OPERATORS__` into the `Build from source` section.

That section is what I followed since it was the most visible; I agree that specifying the complete instructions there is a good idea. Sorry for the duplicate.
