### ISSUE TITLE
`BoundingBox` cannot be deepcopied

### ISSUE THREAD

**Issue by antoinebrl** [pytorch/vision#7698] opened 2023-06-26 21:35 UTC
### 🐛 Describe the bug

As a subclass of Tensor, I would like to deep copy `BoundingBox`.

Code to reproduce
```python
>>> from torchvision.datapoints import BoundingBox, BoundingBoxFormat
>>> bboxes = BoundingBox([[0.,0.,10.,10.],[5.,5.,15.,15.]], format=BoundingBoxFormat.XYXY, spatial_size=(20,20))
>>> from copy import deepcopy
>>> deepcopy(bboxes)
```

Error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...3.10.9/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File ".../.venv/lib/python3.10/site-packages/torch/_tensor.py", line 84, in __deepcopy__
    return handle_torch_function(Tensor.__deepcopy__, (self,), self, memo)
  File ".../.venv/lib/python3.10/site-packages/torch/overrides.py", line 1551, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File ".../.venv/lib/python3.10/site-packages/torchvision/datapoints/_datapoint.py", line 76, in __torch_function__
    output = func(*args, **kwargs or dict())
  File ".../.venv/lib/python3.10/site-packages/torch/_tensor.py", line 170, in __deepcopy__
    raise RuntimeError(
RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works
for subclass types that implement new_empty() and for which that function returns another instance
of the same subclass. You should either properly implement new_empty() for your subclass or override
__deepcopy__() if it is intended behavior for new_empty() to return an instance of a different type.
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (main, Apr 12 2023, 15:10:04) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] hs-infrastructure-flake8-plugins==0.1.2
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.11.3
[pip3] torchvision==0.15.2
[conda] Could not collect
```

**Comment by pmeier** [comment] 2023-06-27 07:25
Duplicate of #6478.

**Closed by pmeier** 2023-06-27 07:25 UTC
