### ISSUE TITLE
An extremely simple cv2 based transform gives black/blank image

### ISSUE THREAD

**Issue by chudur-budur** [pytorch/vision#3756] opened 2021-04-30 00:05 UTC
## 🐛 Bug

I need to write a transform module to be used with `transforms.Compose` that corrects fish-eye distortion. However the code deosn't work and returns a black (all dark) image.

## To Reproduce

The class for distortion correction.
```python
import numpy as np
import cv2

__all__ = ["Unfish"]

class Unfish:
    """Unfish an image.

    If the image is fisheye distorted this class will unfish it.
    """

    def __init__(self, distortion_coeffs=None, camera_intrinsics=None):
        
        self.distortion_coeffs = distortion_coeffs if distortion_coeffs is not None \
                else np.array(\
                [0.20744323318046468, -0.07788465215624041, \
                0.00530138015440915, 0.0032944874130648585])
        
        self.camera_intrinsics = camera_intrinsics if camera_intrinsics is not None \
                else np.array(\
                [626.61271202815, 625.32362717293194, \
                1336.0594825127226, 949.7379173445073])

    def __call__(self, image): 
        # do the transoformation
        fx, fy, cx, cy = self.camera_intrinsics[0], self.camera_intrinsics[1], \
                            self.camera_intrinsics[2], self.camera_intrinsics[3]
        cmat = np.array([[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]])

        # undistort
        mapx, mapy = cv2.fisheye.initUndistortRectifyMap(cmat, self.distortion_coeffs, \
                np.eye(3), cmat, (image.shape[1], image.shape[0]), cv2.CV_16SC2)
        image_ = cv2.remap(image, mapx, mapy, cv2.INTER_LINEAR)
        
        return image_

    def __repr__(self):
       pass
```

Use the above class in `Compose` as below:
```python
    from torchvision import transforms
    unfisher = transforms.Compose([Unfish()])
    image = unfisher(image)
```

The output image is a blank image. However, the if you copy and paste the contents in `__call__` function and run as an independent script, it works just fine. For example,

```python
    unfisher = Unfish()
    image = unfisher.__call__(image)
```

## Expected behavior

The above code should not produce a blank image.

## Environment
```
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.13.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.3.0            py37h54f3939_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch
```

cc @vfdev-5

**Comment by voldemortX** [comment] 2021-04-30 05:49
@chudur-budur Could you try use composed classes as a squence?

For example:

```
for  transform in unfisher:
     image = transform(image)
```

**Comment by pmeier** [comment] 2021-04-30 12:44
@chudur-budur I cannot reproduce your issue. The behavioral change from calling it individually or within a `transforms.Compose` makes little sense, since internally it is also simply called:

https://github.com/pytorch/vision/blob/78ed10cc51067f1a6bac9352831ef37a3f842784/torchvision/transforms/transforms.py#L59-L62

Could you recheck if the inputs are actually the same in both situations? If the issue persists for you, could you please share an image and a complete reproduction including the reading / writing of the image, so we can take a better look?

**Comment by fmassa** [comment] 2021-05-06 13:30
Hi,

I think the issue might be that you are comparing the output of an OpenCV read image (which is between 0-255 in BGR format) while torchvision uses images between 0-1 in RGB format.

Once you fix this, it should work fine.

I believe I've answered the question and as such I'm closing this issue, but let us know if you still face problems

**Closed by fmassa** 2021-05-06 13:30 UTC
Labels: module: transforms, needs reproduction
