### ISSUE TITLE
Failed to download CelebA in Colab

### ISSUE THREAD

**Issue by matteodalessio** [pytorch/vision#2317] opened 2020-06-12 18:44 UTC
## 🐛 Bug

It fails to download the following files **img_align_celeba.zip**

## To Reproduce

1. `from torchvision import datasets`
`trainset = datasets.CelebA(root='./data/', split='train', target_type="attr", transform=transform, download=True)`

Error:
```
Traceback (most recent call last):
  File "transfer_learning.py", line 123, in <module>
    trainset = datasets.CelebA(root='./data/', split='train', transform=transform, download=True)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/celeba.py", line 66, in __init__
    self.download()
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/celeba.py", line 120, in download
    with zipfile.ZipFile(os.path.join(self.root, self.base_folder, "img_align_celeba.zip"), "r") as f:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

## Environment

```
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.0+cu101
[conda] Could not collect
```

**Comment by pmeier** [comment] 2020-06-15 05:14
Duplicate of #1920. @fmassa I'm on it.

**Closed** 2020-07-03 12:52 UTC
