### ISSUE TITLE
Torchvision cuda version should match torch's cuda version

### ISSUE THREAD

**Issue by twoertwein** [pytorch/vision#2713] opened 2020-09-28 02:57 UTC
## 🐛 Bug

Torchvision 0.7.0+cu101 requires pytorch 1.6.0, but it should require 1.6.0+cu101 (or this is a poetry bug/feature).

## To Reproduce

``` sh
$ poetry  add https://download.pytorch.org/whl/cu101/torch-1.6.0%2Bcu101-cp38-cp38-linux_x86_64.whl
$ poetry  add https://download.pytorch.org/whl/cu101/torchvision-0.7.0%2Bcu101-cp38-cp38-linux_x86_64.whl
...
[SolverProblemError]
Because torchvision (0.7.0+cu101) depends on torch (1.6.0)
 and project depends on torch (1.6.0+cu101 url), torchvision is forbidden.
So, because project depends on torchvision (0.7.0+cu101 url), version solving failed.
```

**Comment by fmassa** [comment] 2020-09-28 09:29
Hi,

I believe this is a duplicate of https://github.com/pytorch/vision/issues/2310 .
It is not yet clear if this is a problem that should be fixed in torchvision.

Given that we already have a lot of useful points mentioned in #2310, I propose we continue the discussion there.

**Closed by fmassa** 2020-09-28 09:29 UTC
