### ISSUE TITLE
License Problem of vision

### ISSUE THREAD

**Issue by wqh17101** [pytorch/vision#5839] opened 2022-04-20 07:26 UTC
### 🚀 The feature

As the video related API added in, please care about the license of video component.
 
For example, if you use ffmpeg( with x264(GPL license) ) or pyav (with (ffmpeg with x264)) without process isolation, you will meet the license problem for change vision's license to GPL .

### Motivation, pitch

Watch out that the GPL is contagious. Which will cause big problem to a BSD project.

**Comment by datumbox** [comment] 2022-04-20 09:52
Thanks for reporting. My understanding is that ffmpeg's licensing is the reason why we don't offer precompiled binaries with video support. I'm not too knowledgeable on the topic, so let me cc a few people who know more on the topic than I do.

@fmassa @prabhat00155 @bjuncek Could you provide a summary of the licensing situation?

**Comment by wqh17101** [comment] 2022-04-20 10:50
For pyav you can use ` python -m av --version` to see the real runtime license
like
```
PyAV v9.0.1
library configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
library license: GPL version 3 or later
libavcodec     58. 91.100
libavdevice    58. 10.100
libavfilter     7. 85.100
libavformat    58. 45.100
libavutil      56. 51.100
libswresample   3.  7.100
libswscale      5.  7.100
```
As you can see it is GPL.


The root reason of the license is what FFMPEG built with. The same situation for Pyav.
Something you can check for this. [link](http://ffmpeg.org/legal.html)

So for pyav , the solution is to build pyav by source that you can chose what component of ffmpeg to build with,then pyav will use your custom ffmpeg without GPL component.

**Comment by wqh17101** [comment] 2022-04-20 15:40
I have an idea that you can use `h264_cuvid and nvenc_h264` to replace `libx264` and `hevc_cuvid and nvenc_hevc` to replace `libx265` on GPU vision.

**Comment by bjuncek** [comment] 2022-04-20 17:55
@andfoy was toying with the idea of providing LGPL compatible version of ffmpeg to pytorch channel. Maybe we should pick this up again?

**Comment by andfoy** [comment] 2022-04-20 17:57
We used to provide an LGPL version of FFmpeg that linked against OpenH264, but it was only for 4.2

**Comment by wqh17101** [comment] 2022-04-20 23:22
Never mind, the latest minor updating version is 4.4.2,just update and recompile. @andfoy @bjuncek

**Comment by datumbox** [comment] 2022-05-09 08:51
I've checked with our Open-source and legal teams and they confirmed that:
> TorchVision doesn't have a required dependency on or distribute any GPL library, so there are no issues with the BSD license. We don't prevent a user from combining TorchVision with GPL software, but no GPL software is needed for TorchVision to operate.

I will therefore close the issue as there is no licensing problem in TorchVision.

**Closed by datumbox** 2022-05-09 08:51 UTC
Labels: needs discussion
