### ISSUE TITLE
DatasetFolder class and external functions

### ISSUE THREAD

**Issue by Giaco90** [pytorch/vision#753] opened 2019-02-19 18:25 UTC
Hi there,
i noticed that _make_dataset_ and _find_classes_ are not _DatasetFolder_ methods. Is there a particular reason behind this choice? I need to extend DatasetFolder class to manage classes differently and i need to modify them.
(I know that I can assign to _datasets.folder.make_dataset_ and _datasets.folder._find_classes_ new functions but I don't like the solution a lot.)
Thanks.

**Comment by surgan12** [comment] 2019-02-20 11:36
@Giaco90 As far as I can see the method make_dataset takes a root dir , class to idx, extensions and returns a  list .
This is something very generic and need not be in the class mentioned above.

**Comment by Giaco90** [comment] 2019-02-21 10:49
@surgan12 Yes, but it is strictly related to DatasetFolder class and class_to_idx has been generated by _find_classes that is a DatasetFolder method (furthermore _find_classes behave like make_dataset so the same consideration should be done for it).
However i agree that it is generic, but at the same time it is related do DatasetFolder (since i can't find other useful occurrences), so maybe it could be passed as a default in the constructor.

Thank for your reply.

**Comment by surgan12** [comment] 2019-02-27 07:32
@fmassa What do you think on this ?

**Comment by surgan12** [comment] 2019-03-05 06:15
@vishwakftw, i think this can be closed .

**Comment by vishwakftw** [comment] 2019-03-05 06:16
@Giaco90 if you think that the issue is resolved, please close it. Thank you.

**Closed** 2019-03-06 19:55 UTC
