### ISSUE TITLE
Deformable convolution fails when batch size is more than 32?

### ISSUE THREAD

**Issue by shreyaskamathkm** [pytorch/vision#2817] opened 2020-03-10 16:16 UTC
## 🐛 Bug

Deformable convolution fails when batch size is more than 32. To check if this is a regular behavior, it was tested against the implementation provided in [mmdetection](https://github.com/open-mmlab/mmdetection). That implementation works for any batch size.

Trace:

```
Traceback (most recent call last):

  File "/mnt/1260D2E260D2CC1B/Nutrition_Pytorch/Classification/debug/deform_test.py", line 42, in <module>
    output = model(img)

  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "/mnt/1260D2E260D2CC1B/Nutrition_Pytorch/Classification/debug/deform_test.py", line 32, in forward
    return deform_conv2d(input = x, offset= offset, weight= self.weight, stride=_pair(self.stride),padding= _pair(self.padding), dilation=_pair(self.dilation))

  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/torchvision/ops/deform_conv.py", line 76, in deform_conv2d
    n_offset_grps)

RuntimeError: shape '[1, 1, 288]' is invalid for input of size 158957568
```
## Expected behavior

```
import torch
from torchvision.ops import DeformConv2d
import torch.nn as nn
from torch.nn.modules.utils import _pair
from torchvision.ops import deform_conv2d

class DeformConvPack(DeformConv2d):
    def __init__(self, *args, **kwargs):
        super(DeformConvPack, self).__init__(*args, **kwargs)

        self.conv_offset = nn.Conv2d(
            self.in_channels,
            2 * 2 * self.kernel_size[0] * self.kernel_size[1],
            kernel_size=self.kernel_size,
            stride=_pair(self.stride),
            padding=_pair(self.padding),
            bias=True)
        self.init_offset()

    def init_offset(self):
        self.conv_offset.weight.data.zero_()
        self.conv_offset.bias.data.zero_()

    def forward(self, x):
        offset = self.conv_offset(x)
        return deform_conv2d(input = x, offset= offset, weight= self.weight, stride=_pair(self.stride),padding= _pair(self.padding), dilation=_pair(self.dilation))



if __name__ == '__main__':
    img = torch.randn(32, 32, 224, 224).cuda()
    model = DeformConvPack(32 ,64,3,padding =1).cuda()
    output = model(img)
```

## Environment Information:

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.04
GCC version: (Ubuntu 8.3.0-6ubuntu1) 8.3.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.26
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.4.0
[pip] torchtext==0.5.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.5.0                py37_cu101    pytorch

```

cc @ngimel @fmassa @vfdev-5

**Comment by vfdev-5** [comment] 2020-10-14 19:18
@datumbox could you please reproduce this : https://github.com/pytorch/vision/issues/2817#issuecomment-708593829 ?
Most probably, it was already fixed in master...

**Comment by fmassa** [comment] 2020-10-14 19:51
We have fixed DeformableConv2d support for batches larger than 32 in https://github.com/pytorch/vision/pull/2040

For @happywu message, please open a new issue with a self-contained minimal example that reproduces the error. You might just be facing memory issues while trying to allocate that tensor.

**Closed by fmassa** 2020-10-14 19:51 UTC

**Comment by datumbox** [comment] 2020-10-14 20:17
@vfdev-5 My laptop's GPU can't fit all the data. Nevertheless the following runs fine against 0.7.0:
```
#...
img = torch.randn(32, 32, 112, 112).cuda()
#...
```

**Comment by vfdev-5** [comment] 2020-10-14 20:20
@datumbox thanks a lot !

**Comment by abhiagwl4262** [comment] 2022-08-01 12:28
I got this error whille running the code mentioned in the isssue. 

`NotImplementedError: Could not run 'torchvision::deform_conv2d' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::deform_conv2d' is only available for these backends: [Dense, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].`

Is deform-conv only supported for CPU ?
