### ISSUE TITLE
Batch support for torchvision.transforms.functional

### ISSUE THREAD

**Issue by Shubhammawa** [pytorch/vision#2546] opened 2020-08-03 08:08 UTC
Support for a batch of images in torchvision.transforms.functional.

Currently the torchvision.transforms.functional transformations take only a single image as input. Sometimes after creating the dataloader, I need to transform the images during the training loop, but passing the batch of images to transforms.functional raises an error expecting a 2/3 dimensional input while it gets a 4-dimensional input. I am currently solving the issue by looping through the images in the batch but it would be nice if the transforms could handle a batch of images on their own.

**Comment by fmassa** [comment] 2020-08-03 09:11
Hi,

We are progressively adding support for tensors inputs in the `transforms.functional`, and with this it will have support for batch of images as well.

See
https://github.com/pytorch/vision/blob/62e3fbd82a7e6c9c6455af57cf8c4191035c90d4/torchvision/transforms/functional_tensor.py#L594-L596
which gets dispatched to from `torchvision.transforms.functional.resize` when the input is a tensor https://github.com/pytorch/vision/issues/2292

As such, I'm closing this as a duplicate of https://github.com/pytorch/vision/issues/1375

**Closed by fmassa** 2020-08-03 09:11 UTC
