### ISSUE TITLE
Link to Stanford cars dataset is broken: 404 not found

### ISSUE THREAD

**Issue by jdenholm** [pytorch/vision#7930] opened 2023-09-02 09:43 UTC
### 📚 The doc issue

The link to the Stanford cars dataset, [here](https://ai.stanford.edu/~jkrause/cars/car_dataset.html), on [this page](https://pytorch.org/vision/stable/generated/torchvision.datasets.StanfordCars.html#torchvision.datasets.StanfordCars), gives a 404 not found.

**Comment by pmeier** [comment] 2023-09-04 07:33
Duplicate of #7545.

**Closed by pmeier** 2023-09-04 07:33 UTC
