### ISSUE TITLE
[C++ Frontend] Most tests fail on OSX

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#1191] opened 2019-08-01 14:01 UTC
I've just tried running the tests for the C++ frontend on an OSX, with PyTorch nightly from today and torchvision from master, and most tests fail with an error similar to the following:

```
Traceback (most recent call last):
  File "test/test_cpp_models.py", line 43, in test_alexnet
    process_model(models.alexnet(self.pretrained), self.image, _C_tests.forward_alexnet, 'Alexnet')
  File "test/test_cpp_models.py", line 16, in process_model
    cpp_output = func("model.pt", tensor)
RuntimeError: new_refcount != 1 INTERNAL ASSERT FAILED at /Users/fmassa/anaconda3/lib/python3.6/site-packages/torch/include/c10/util/intrusive_ptr.h:185, please report a bug to PyTorch. intrusive_ptr: Cannot increase refcount after it reached zero. (retain_ at /Users/fmassa/anaconda3/lib/python3.6/site-packages/torch/include/c10/util/intrusive_ptr.h:185)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x111340917 in libc10.dylib)
frame #1: c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::retain_() + 360 (0x11f9b3dd8 in _C_tests.cpython-36m-darwin.so)
frame #2: at::Tensor std::__1::__invoke_void_return_wrapper<at::Tensor>::__call<at::Tensor& (*&)(at::Tensor), at::Tensor>(at::Tensor& (*&&&)(at::Tensor), at::Tensor&&) + 124 (0x11f9dbe6c in _C_tests.cpython-36m-darwin.so)
frame #3: std::__1::__function::__func<at::Tensor& (*)(at::Tensor), std::__1::allocator<at::Tensor& (*)(at::Tensor)>, at::Tensor (at::Tensor)>::operator()(at::Tensor&&) + 18 (0x11f9dbdb2 in _C_tests.cpython-36m-darwin.so)
frame #4: torch::nn::FunctionalImpl::forward(at::Tensor) + 53 (0x115d98a55 in libtorch.dylib)
frame #5: torch::nn::AnyModule::Value torch::nn::AnyModule::Holder<torch::nn::FunctionalImpl, at::Tensor>::InvokeForward::operator()<at::Tensor>(at::Tensor&&) + 54 (0x11f9e03f6 in _C_tests.cpython-36m-darwin.so)
frame #6: torch::nn::AnyModule::Holder<torch::nn::FunctionalImpl, at::Tensor>::forward(std::__1::vector<torch::nn::AnyModule::Value, std::__1::allocator<torch::nn::AnyModule::Value> >&&) + 86 (0x11f9dffe6 in _C_tests.cpython-36m-darwin.so)
frame #7: torch::nn::AnyModule::Value torch::nn::AnyModule::any_forward<torch::nn::AnyModule::Value>(torch::nn::AnyModule::Value&&) + 168 (0x11f9cad48 in _C_tests.cpython-36m-darwin.so)
frame #8: at::Tensor torch::nn::SequentialImpl::forward<at::Tensor, at::Tensor&>(at::Tensor&&&) + 94 (0x11f9c86ce in _C_tests.cpython-36m-darwin.so)
frame #9: vision::models::AlexNetImpl::forward(at::Tensor) + 68 (0x11f9d5e94 in _C_tests.cpython-36m-darwin.so)
frame #10: at::Tensor forward_model<vision::models::AlexNet>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor) + 107 (0x11f9ae76b in _C_tests.cpython-36m-darwin.so)
frame #11: forward_alexnet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor) + 49 (0x11f9ae641 in _C_tests.cpython-36m-darwin.so)
frame #12: at::Tensor pybind11::detail::argument_loader<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor>::call_impl<at::Tensor, at::Tensor (*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor), 0ul, 1ul, pybind11::detail::void_type>(at::Tensor (*&&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor), pybind11::detail::index_sequence<0ul, 1ul>, pybind11::detail::void_type&&) + 42 (0x11f9b931a in _C_tests.cpython-36m-darwin.so)
frame #13: void pybind11::cpp_function::initialize<at::Tensor (*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor), at::Tensor, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor, pybind11::name, pybind11::scope, pybind11::sibling, char [16]>(at::Tensor (*&&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor), at::Tensor (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, at::Tensor), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const (&) [16])::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 89 (0x11f9b8a29 in _C_tests.cpython-36m-darwin.so)
frame #14: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3392 (0x11f9ba6e0 in _C_tests.cpython-36m-darwin.so)
<omitting python frames>
```

cc @ShahriarSS

**Comment by ShahriarSS** [comment] 2019-08-01 14:31
The problem is most likely in tests bindings and not in the models themselves. I'll look into it.

**Comment by datumbox** [comment] 2020-10-26 14:45
I recently tried running the tests on macOS. All pass except:
- MNASNet0_5
- MNASNet0_75
- MNASNet1_3

Error message:
```
test/test_cpp_models.py:136 (Tester.test_mnasnet1_3)
self = <test_cpp_models.Tester testMethod=test_mnasnet1_3>

    def test_mnasnet1_3(self):
>       process_model(models.mnasnet1_3(self.pretrained), self.image, _C_tests.forward_mnasnet1_3, 'MNASNet1_3')

test/test_cpp_models.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

model = MNASNet(
  (layers): Sequential(
    (0): Conv2d(3, 40, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)...Sequential(
    (0): Dropout(p=0.2, inplace=True)
    (1): Linear(in_features=1280, out_features=1000, bias=True)
  )
)
tensor = tensor([[[[0.0902, 0.1059, 0.1059,  ..., 0.2863, 0.2667, 0.2784],
          [0.1059, 0.0980, 0.1059,  ..., 0.3098, 0.3...41, 0.1059, 0.0824,  ..., 0.0667, 0.0784, 0.0706],
          [0.0902, 0.1059, 0.0784,  ..., 0.0667, 0.0706, 0.0667]]]])
func = <built-in method forward_mnasnet1_3 of PyCapsule object at 0x7fcba9eb2d50>
name = 'MNASNet1_3'

    def process_model(model, tensor, func, name):
        model.eval()
        traced_script_module = torch.jit.trace(model, tensor)
        traced_script_module.save("model.pt")
    
        py_output = model.forward(tensor)
>       cpp_output = func("model.pt", tensor)
E       RuntimeError: Given groups=32, expected weight to be divisible by 32 at dimension 0, but got weight of size [[40, 1, 3, 3]] instead

test/test_cpp_models.py:22: RuntimeError
```

**Comment by datumbox** [comment] 2021-12-02 17:03
@fmassa Give the deprecation of the C++ model classes, does it make sense to close the issue?

**Comment by ameroueh** [comment] 2021-12-02 20:10
I was able to reproduce this issue on a linux box as well

**Comment by ameroueh** [comment] 2021-12-02 20:11
> I recently tried running the tests on macOS. All pass except:
> 
>     * MNASNet0_5
> 
>     * MNASNet0_75
> 
>     * MNASNet1_3
> 
> 
> Error message:
> 
> ```
> test/test_cpp_models.py:136 (Tester.test_mnasnet1_3)
> self = <test_cpp_models.Tester testMethod=test_mnasnet1_3>
> 
>     def test_mnasnet1_3(self):
> >       process_model(models.mnasnet1_3(self.pretrained), self.image, _C_tests.forward_mnasnet1_3, 'MNASNet1_3')
> 
> test/test_cpp_models.py:138: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> model = MNASNet(
>   (layers): Sequential(
>     (0): Conv2d(3, 40, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)...Sequential(
>     (0): Dropout(p=0.2, inplace=True)
>     (1): Linear(in_features=1280, out_features=1000, bias=True)
>   )
> )
> tensor = tensor([[[[0.0902, 0.1059, 0.1059,  ..., 0.2863, 0.2667, 0.2784],
>           [0.1059, 0.0980, 0.1059,  ..., 0.3098, 0.3...41, 0.1059, 0.0824,  ..., 0.0667, 0.0784, 0.0706],
>           [0.0902, 0.1059, 0.0784,  ..., 0.0667, 0.0706, 0.0667]]]])
> func = <built-in method forward_mnasnet1_3 of PyCapsule object at 0x7fcba9eb2d50>
> name = 'MNASNet1_3'
> 
>     def process_model(model, tensor, func, name):
>         model.eval()
>         traced_script_module = torch.jit.trace(model, tensor)
>         traced_script_module.save("model.pt")
>     
>         py_output = model.forward(tensor)
> >       cpp_output = func("model.pt", tensor)
> E       RuntimeError: Given groups=32, expected weight to be divisible by 32 at dimension 0, but got weight of size [[40, 1, 3, 3]] instead
> 
> test/test_cpp_models.py:22: RuntimeError
> ```

I was able to reproduce the same tests failing on a linux box as well

**Closed** 2021-12-06 10:04 UTC
Labels: bug, help wanted, module: models, module: c++ frontend
