### ISSUE TITLE
[proto] Port detection transforms from reference

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#6393] opened 2022-08-10 16:05 UTC
Transforms to port from [detection references](https://github.com/pytorch/vision/blob/main/references/detection/transforms.py) :

- [ ] RandomIoUCrop (@vfdev-5)
- [ ] ScaleJitter
- [ ] FixedSizeCrop
- [ ] RandomShortestSize
- [ ] SimpleCopyPaste

cc @vfdev-5 @datumbox @bjuncek @pmeier

**Comment by pmeier** [comment] 2022-08-11 08:30
Duplicate of #5542.

**Closed by pmeier** 2022-08-11 08:30 UTC
Labels: module: transforms, prototype
