### ISSUE TITLE
Error closing: 'NoneType' object has no attribute 'close' for ImageNet reading

### ISSUE THREAD

**Issue by Randl** [pytorch/vision#305] opened 2017-10-20 10:07 UTC
When loading ImageNet, I get the following debug messages
`Error closing: 'NoneType' object has no attribute 'close' for ImageNet reading`
message called from https://github.com/pytorch/vision/blob/45dab0e4528333332f07ab1979e006857563cf99/torchvision/datasets/folder.py#L46

caused by
https://github.com/python-pillow/Pillow/blob/7d8c0d9e39d5ed79ea6aa590b9cbff5b0d17248c/PIL/Image.py#L573

**Comment by alykhantejani** [comment] 2017-10-23 09:54
This would suggest the `img` is `None`. Are you sure you are setting the `root` and `transform` correctly in the `ImageFolder` constructor?  Could you pose a minimum working example?

**Comment by Randl** [comment] 2017-10-23 11:49
@alykhantejani The network works fine, and img seems to be assigned None after usage or something. An (not that minimal) example is that code: https://github.com/eladhoffer/convNet.pytorch running on ImageNet

**Comment by alykhantejani** [comment] 2017-10-23 12:01
@Randl does this issue happen on a specific image/specific images? It might be a corrupt image in your download

**Comment by Randl** [comment] 2017-10-23 17:32
@alykhantejani it looks like it happens for every single image

**Comment by alykhantejani** [comment] 2017-10-23 17:34
@Randl hmm that's very strange indeed. Does this also happen with the MNIST example? (Just trying to find a MWE that I can run over here). 

Let me know about MNIST, I'll take a look at this tomorrow and try and reproduce on my end - thanks for reporting!

**Comment by eladhoffer** [comment] 2017-11-10 12:59
@Randl did you find a solution for this?

**Comment by alykhantejani** [comment] 2017-11-28 22:00
This could be related to this post on the forum: https://discuss.pytorch.org/t/debug-pil-image-error-closing-nonetype-object-has-no-attribute-close/10489

**Comment by alykhantejani** [comment] 2017-11-28 22:06
Ah ok upon looking deeper into this, it seems that PILs image `close` function states in the docstring:
```
    def close(self):
        """
        Closes the file pointer, if possible.
        This operation will destroy the image core and release its memory.
        The image data will be unusable afterward.
        This function is only required to close images that have not
        had their file read and closed by the
        :py:meth:`~PIL.Image.Image.load` method.
        """
```

And if we look into the `img.convert` we can see that `load` is called [here](https://github.com/python-pillow/Pillow/blob/7d8c0d9e39d5ed79ea6aa590b9cbff5b0d17248c/PIL/Image.py#L875), which explains the exception thrown when the image is closed.

To "avoid" this, you should either not set your logging level to "debug", or use a logger that's rooted to your application i.e. give your logger a name. 

Closing this as it seems to be a wont-fix from our end. Happy to re-open if you think it needs something done from our side

**Comment by Randl** [comment] 2017-12-04 14:20
@alykhantejani So the call of `close` isn't actually required?

**Comment by alykhantejani** [comment] 2017-12-04 15:46
@Randl yup - this can actually be "solved" by not using the `Image` as a context manager in the  `ImageFolder` [here](https://github.com/pytorch/vision/blob/45dab0e4528333332f07ab1979e006857563cf99/torchvision/datasets/folder.py#L45).


Will re-open the issue here and will "fix" soon

**Closed** 2017-12-06 11:15 UTC
