### ISSUE TITLE
ImageNet Downloader - Dead Links

### ISSUE THREAD

**Issue by Delaunay** [pytorch/vision#1510] opened 2019-10-21 15:24 UTC
The imagenet downloader seems to use dead links.

Test Script:

```python
from torchvision.datasets import ImageNet


train = ImageNet('/fast/ImageNet/train', split='train', download=True)
val = ImageNet('/fast/ImageNet/val', split='val', download=True)
```

Output:

```python
0it [00:00, ?it/s]Downloading http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_devkit_t12.tar.gz to /fast/ImageNet/train/ILSVRC2012_devkit_t12.tar.gz
Traceback (most recent call last):
  File "/home/setepenre/work/mlbaselines/mlbaselines/datasets/__init__.py", line 4, in <module>
    train = ImageNet('/fast/ImageNet/train', split='train', download=True)
  File "/home/setepenre/miniconda3/lib/python3.7/site-packages/torchvision/datasets/imagenet.py", line 55, in __init__
    self.download()
  File "/home/setepenre/miniconda3/lib/python3.7/site-packages/torchvision/datasets/imagenet.py", line 75, in download
    md5=archive_dict['md5'])
  File "/home/setepenre/miniconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 248, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/setepenre/miniconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 96, in download_url
    raise e
  File "/home/setepenre/miniconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 84, in download_url
    reporthook=gen_bar_updater()
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/setepenre/miniconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
0it [00:01, ?it/s]
```

**Comment by fmassa** [comment] 2019-10-21 15:33
Duplicate of https://github.com/pytorch/vision/issues/1453

**Closed by fmassa** 2019-10-21 15:33 UTC
