### ISSUE TITLE
torchvision.datasets.ImageFolder

### ISSUE THREAD

**Issue by IlSLY** [pytorch/vision#707] opened 2019-01-04 05:34 UTC
**Environment:**
 macOS Mojave
torchvision 0.2.1
pytorch 1.0.0
python  3.6.7

my problem shows as following:
>>> import torchvision
>>> dataset=torchvision.datasets.ImageFolder('/Users/administer/Desktop/D-HAZY_DATASET1/Middlebury_Hazy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 79, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /Users/administer/Desktop/D-HAZY_DATASET1/Middlebury_Hazy
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

But there have images, they are 'bmp' format in that path. Could anyone tell me how can I fix this problem?

**Comment by hubutui** [comment] 2019-01-05 12:42
check file extension, and https://discuss.pytorch.org/ is a better place for discussion.

**Comment by varunagrawal** [comment] 2019-01-21 23:50
Your error is here: `RuntimeError: Found 0 files in subfolders of: /Users/administer/Desktop/D-HAZY_DATASET1/Middlebury_Hazy`

That directory seems to be empty. Can you double check to make sure? This seems to be a valid bug.

**Comment by fmassa** [comment] 2019-01-22 16:23
As the others have said, your dataset is empty and the error is raised in
https://github.com/pytorch/vision/blob/98ca260bc834ec94a8143e4b5cfe9516b0b951a2/torchvision/datasets/folder.py#L86-L87

I'd say that it's better to raise an error in this case than to silently pass (and have unexpected behavior), thus I'm closing this issue but let me know if you disagree

**Closed by fmassa** 2019-01-22 16:23 UTC

**Comment by fatemeakbari** [comment] 2019-04-08 12:45
hello
you have to create a sub directory in your images directory, 
e.g if images directory is:
./VOC2007/JPEGImages
dataset=torchvision.datasets.ImageFolder('./VOC2007')

**Comment by duskybomb** [comment] 2019-06-27 21:05
pytorch=1.0.1
torchvision=0.2.2
ubuntu=18.04
python=3.7.2

I am getting the same error and I have verified that there are 15000 jpg images.
```
>>> image_dataset = {x: datasets.ImageFolder(os.path.join(data_dir, x),
                     data_transforms[x]) for x in ['train', 'val']}
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <dictcomp>
  File "/home/duskybomb/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    target_transform=target_transform)
  File "/home/duskybomb/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 87, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: ../../kaggle/aerial-cactus-detection/train/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,webp
```
