### ISSUE TITLE
Program stuck when using models.inception_v3()

### ISSUE THREAD

**Issue by Mercurialzhang** [pytorch/vision#1977] opened 2020-03-13 12:44 UTC
When I create the model with `models.inception_v3()`, the program is completely stuck, it's okay with other models like `models.resnet50()`

My torch and torchvison version is 1.4.0 and 0.5.0.

Looking forward to your help.

**Comment by fmassa** [comment] 2020-03-13 13:06
Hi,

Thanks for the bugreport! This is a duplicate of https://github.com/pytorch/vision/issues/1797

This has been fixed in latest version torchvision, via the `init_weights` argument, so one option would be to update torchvision (and pytorch) to a nightly version, or downgrading your scipy install

**Closed by fmassa** 2020-03-13 13:06 UTC
