### ISSUE TITLE
Error while loading pretrained Inception (v 0.2.1)

### ISSUE THREAD

**Issue by DSLituiev** [pytorch/vision#480] opened 2018-04-26 17:50 UTC
Dimension mismatch error while loading a pretrained Inception v3

### Environment
0.2.1 with Anaconda, python3.6, Ubuntu 16

### code
    from torchvision.models.inception import Inception3, inception_v3
    model = inception_v3(num_classes=1, pretrained=True, aux_logits=False)

### error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-31-e0b4dcd6b958> in <module>()
----> 1 model = inception_v3(num_classes=1, pretrained=True, aux_logits=False)

/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/inception.py in inception_v3(pretrained, **kwargs)
     25             kwargs['transform_input'] = True
     26         model = Inception3(**kwargs)
---> 27         model.load_state_dict(model_zoo.load_url(model_urls['inception_v3_google']))
     28         return model
     29 

/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    719         if len(error_msgs) > 0:
    720             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 721                                self.__class__.__name__, "\n\t".join(error_msgs)))
    722 
    723     def parameters(self):

RuntimeError: Error(s) in loading state_dict for Inception3:
	Unexpected key(s) in state_dict: "AuxLogits.conv0.conv.weight", "AuxLogits.conv0.bn.weight", "AuxLogits.conv0.bn.bias", "AuxLogits.conv0.bn.running_mean", "AuxLogits.conv0.bn.running_var", "AuxLogits.conv1.conv.weight", "AuxLogits.conv1.bn.weight", "AuxLogits.conv1.bn.bias", "AuxLogits.conv1.bn.running_mean", "AuxLogits.conv1.bn.running_var", "AuxLogits.fc.weight", "AuxLogits.fc.bias". 
	While copying the parameter named "fc.weight", whose dimensions in the model are torch.Size([1, 2048]) and whose dimensions in the checkpoint are torch.Size([1000, 2048]).
	While copying the parameter named "fc.bias", whose dimensions in the model are torch.Size([1]) and whose dimensions in the checkpoint are torch.Size([1000]).

```

**Comment by moskomule** [comment] 2018-04-27 05:26
It's because you specify `num_classes=1`. Try `inception_v3(num_classes=1000, pretrained=True)` instead. Then, if you like 1 class output, replace the `model.fc`.

**Comment by fmassa** [comment] 2018-04-27 09:42
@moskomule 's answer will solve your issue. Closing as not a bug

**Closed by fmassa** 2018-04-27 09:42 UTC

**Comment by fmassa** [comment] 2018-04-27 17:41
You mean a PR in `examples`? Or a PR in torchvision mentioning that `inception` requires a different input size? I'd vote for the second option

**Comment by fmassa** [comment] 2018-04-27 17:47
I think a PR for torchvision would be great actually!

**Comment by luyao777** [comment] 2018-09-16 05:40
When I let aux_logits=True, it gives me

>  RuntimeError
Calculated padded input size per channel: (3 x 3). Kernel size: (5 x 140707423584261). Kernel size can't greater than actual input size at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/THNN/generic/SpatialConvolutionMM.c:48

when I let aux_logit=False, it gives me

> RuntimeError
Error(s) in loading state_dict for Inception3:   Unexpected key(s) in state_dict: "AuxLogits.conv0.conv.weight", "AuxLogits.conv0.bn.weight", "AuxLogits.conv0.bn.bias", "AuxLogits.conv0.bn.running_mean", "AuxLogits.conv0.bn.running_var", "AuxLogits.conv1.conv.weight", "AuxLogits.conv1.bn.weight", "AuxLogits.conv1.bn.bias", "AuxLogits.conv1.bn.running_mean", "AuxLogits.conv1.bn.running_var", "AuxLogits.fc.weight", "AuxLogits.fc.bias".

**Comment by lucygan** [comment] 2018-11-04 12:50
@moskomule  sorry but how to modify the model.fc to avoid those mistakes? I've already changed the num_classes to 8, see as model = inception_v3(pretrained=True, num_classes=8, aux_logits=False), but still get the same mistakes.

**Comment by Kachakhiladi** [comment] 2019-04-27 06:18
I have the same error as the original poster. 

The error is not due to the num_classes. It is due to aux_logits=False instead of the default aux_logits=True. 
Any leads ?

**Comment by XiaolingLuo** [comment] 2019-09-01 08:24
You should not modify the "model = models.inception_v3(pretrained=True)", because if you change the code here, it will have errors in  "load_state_dict". 
Try: 
               "model  = models.inception_v3(pretrained=True)
                model.aux_logits = False
                num_ftrs = model.fc.in_features
                model.fc = nn.Linear(num_ftrs, nclasses) "

**Comment by luciagan** [comment] 2019-09-13 08:56
Dear Shirley,

Thanks for your reply.

Best,
Lei Gan



On Sep 1, 2019, at 16:24, ShirleyLuo <notifications@github.com<mailto:notifications@github.com>> wrote:


You should not modify the "model = models.inception_v3(pretrained=True)", because if you change the code here, it will have errors in "load_state_dict".
Try:
"model = models.inception_v3(pretrained=True)
model.aux_logits = False
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, nclasses) "
