### ISSUE TITLE
Failing to load the pre-trained weights on multi-gpus.

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/vision#3767] opened 2021-05-03 21:33 UTC
## 🐛 Bug

Downloading the pre-trained weights for following models, Alexnet, Resnet_152, Resnet -18, SqueezeNet, VGG11 and trying to load them on any gpu other than cuda:0, it throw error.

## To Reproduce

wget https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth

```
import torch
from torchvision.models.alexnet import AlexNet
class ImageClassifier(AlexNet):
    def __init__(self):
        super(ImageClassifier, self).__init__()             
device1='cuda:0'
device2='cuda:2'
model = ImageClassifier()
state_dict = torch.load("alexnet-owt-4df8aa71.pth", map_location=device2)
model.load_state_dict(state_dict)
model = model.to(device2)
```

## Error 
_File "test_device.py", line 16, in
state_dict = torch.load("alexnet-owt-4df8aa71.pth", map_location=device2)........_

_RuntimeError: Attempted to set the storage of a tensor on device "cuda:0" to a storage on different device "cuda:2". This is no longer allowed; the devices must match_

## Expected behavior

Be able to load the state_dict on any cuda device using map_location.

## Enviroment
 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0):1.7.1, 1.8.0,1.8.1
 - OS (e.g., Linux): ubuntu 18.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:10.2
 - GPU models and configuration: Nvidia Tesla k80
 - Any other relevant information:

## Additional context
These models are being used in Torchserve examples are failing in multi-gpu setting to be loaded on different cuda device. As a work around in Torchserve stated dicts are loaded first  on cuda:0 then move the model to another device/ cuda+ids which creates this  [issue](https://github.com/pytorch/serve/issues/1037) where it results in duplicated processes on two gpus and adding to the memory footprint.

**Comment by vfdev-5** [comment] 2021-05-04 08:38
@HamidShojanazeri how about loading on cpu and then moving it to device2:
```python
state_dict = torch.load("alexnet-owt-4df8aa71.pth", map_location="cpu")
model.load_state_dict(state_dict)
model = model.to(device2)
```
By the way, the model is on cpu as well.

**Comment by fmassa** [comment] 2021-05-04 10:01
Hi,

This is probably related to #2068 -- some of the oldest model checkpoints in torchvision have been serialized with an old version of the serialization script, which could be the culprit here.

Note that we have re-uploaded the checkpoints and updated the model links recently. This fix is present in the torchvision nigthlies and will be available in the next release.

Can you double-check that with the latest checkpoints you don't face this issue anymore?

**Comment by NicolasHug** [comment] 2021-05-04 10:29
I can't reproduce the issue using the latest AlexNet weights https://download.pytorch.org/models/alexnet-owt-7be5be79.pth

**Comment by fmassa** [comment] 2021-05-04 12:19
FYI we still need to update some weights, see https://github.com/pytorch/vision/issues/2473 for more info.

We will be doing this shortly

**Comment by HamidShojanazeri** [comment] 2021-05-10 16:49
Thanks @fmassa for the updates and comments, I wonder what version of serialization / PT has been used for these models, this will help the community/ Torchserve users in case there are any older checkpoints.

**Comment by fmassa** [comment] 2021-05-17 12:26
> Thanks @fmassa for the updates and comments, I wonder what version of serialization / PT has been used for these models, this will help the community/ Torchserve users in case there are any older checkpoints.

Those were very old versions of PyTorch, prior to PyTorch 0.2 I believe.

**Closed** 2021-05-17 15:31 UTC
Labels: question

**Comment by jagadeeshi2i** [comment] 2023-08-22 16:03
@HamidShojanazeri Even this model weights should be updated -https://torchserve.pytorch.org/mar_files/resnet-152-batch_v2.mar - https://github.com/pytorch/serve/issues/2467
