### ISSUE TITLE
Non-writable numpy arrays in MNIST dataset

### ISSUE THREAD

**Issue by catalys1** [pytorch/vision#4353] opened 2021-09-02 16:15 UTC
### 🐛 Describe the bug

When instantiating `torchvision.datasets.MNIST`, I get the following warning:

```bash
/home/catalys1/venv/lib/python3.7/site-packages/torchvision/datasets/mnist.py:498: UserWarning: 
The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. 
This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. 
You may want to copy the array to protect its data or make it writeable before converting it to a tensor. 
This type of warning will be suppressed for the rest of this program. (Triggered internally at 
/pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
```

It seems like datasets that are stored and accessed as numpy arrays may need to be updated: perhaps by changing `np.asarray` to `np.array`, or else performing a copy of the data, before being converted to a `torch.tensor`. 

### Versions

```bash
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.9

Python version: 3.7.0 (default, Sep 26 2018, 13:15:15)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-81-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect
```

**Comment by NicolasHug** [comment] 2021-09-02 16:18
Thanks for the report @catalys1 , I believe this is a duplicate of https://github.com/pytorch/vision/issues/4183 which has already been fixed and will be available in the next release.

I'll close the issue, but if you can still observe the same issue with the nightly-release of torchvision please re-open it!

**Closed by NicolasHug** 2021-09-02 16:18 UTC
