### ISSUE TITLE
I got an error when loading deeplabv3_resnet101.

### ISSUE THREAD

**Issue by tuxxon** [pytorch/vision#4277] opened 2021-08-16 04:24 UTC
## 🐛 Bug

I got the error when running `model = torch.hub.load('pytorch/vision:v0.10.0', 'deeplabv3_resnet101', pretrained=True)` 

## To Reproduce

1.  Click the url below: <br/> https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/pytorch_vision_deeplabv3_resnet101.ipynb
2. Click the first cell
```
import torch
model = torch.hub.load('pytorch/vision:v0.10.0', 'deeplabv3_resnet101', pretrained=True)
model.eval()
```

## Expected behavior

Normal works.

but, I got this error:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-2-90f9efc58017> in <module>()
      1 import torch
----> 2 model = torch.hub.load('pytorch/vision:v0.10.0', 'deeplabv3_resnet101', pretrained=True)
      3 model.eval()

8 frames
/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: rate limit exceeded
```
## Environment

Jupyter notebook with Python3

**Comment by NicolasHug** [comment] 2021-08-16 06:58
Thanks for the report, this is a known issue that should be fixed in the next version. I'll close as a duplicate of https://github.com/pytorch/vision/issues/4156 and https://github.com/pytorch/pytorch/issues/61755

I your specific case, could you try to load the model directly from torchvision instead:

```py
model = torchvision.models.deeplabv3_resnet101(pretrained=True, progress=True)
```
This will only be equivalent if you have torchvision 0.10 though.

Otherwise you can also set

```py
torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
```

as described in https://github.com/pytorch/pytorch/issues/61755#issuecomment-885801511
model = torchvision.models.densenet121(pretrained=True, progress=True)

**Closed by NicolasHug** 2021-08-16 06:58 UTC
