### ISSUE TITLE
`from torchvision.datasets import *` i can't through this way import MovingMNIST

### ISSUE THREAD

**Issue by zyq213** [pytorch/vision#8704] opened 2024-11-01 03:00 UTC
### 🐛 Describe the bug

`from torchvision.datasets import *`
i can't through this way import MovingMNIST
__init__.py missing MovingMNIST in __all__ list
![image](https://github.com/user-attachments/assets/d30ab2e9-f768-4fd7-b6bd-217a075740e8)

### Versions

torchvision：0.15.2+cu118

**Comment by abhi-glitchhg** [comment] 2024-11-01 10:06
I can reproduce the error (even for main branch). The reason is MovingMNIST is missing from the following list.
https://github.com/pytorch/vision/blob/fa99a5360fbcd1683311d57a76fcc0e7323a4c1e/torchvision/datasets/__init__.py#L59-L100


@zyq213 Would you like to send fix for this?

**Comment by NicolasHug** [comment] 2024-11-01 10:35
Thanks for the report @zyq213  and for the help @abhi-glitchhg , I fixed it in  https://github.com/pytorch/vision/pull/8705

**Closed** 2024-11-01 10:35 UTC
