### ISSUE TITLE
Torchvision MaskRCNN only accepts squared inputs

### ISSUE THREAD

**Issue by RiSaMa** [pytorch/vision#1030] opened 2019-06-17 09:12 UTC
The documentation clearly shows that the input to the detection models (e.g. MaskRCNN) can be of any size following CxHxW.

The example in the documentation is as follows:
```
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)
```

However, I obtain this error:
> RuntimeError: The expanded size of the tensor (1056) must match the existing size (1066) at non-singleton dimension 2.  Target sizes: [3, 800, 1056].  Tensor sizes: [3, 800, 1066]

However, if the inputs are square:
`x = [torch.rand(3, 300, 300), torch.rand(3, 400, 400)]`

Everything works smoothly. **Am I missing something or is this a bug?**

Thanks

**Comment by fmassa** [comment] 2019-06-17 09:29
This is not expected, and the model is supposed to work on any input size.

Can you paste the full stack trace?
Also, can your give the result of
```
print(torch.__version__)
print(torchvision.__version__)
```
and paste it here?

**Comment by RiSaMa** [comment] 2019-06-17 10:50
Thank you for your prompt answer. 

**Code:**
```
import torch
import torchvision
import logging

print(torch.__version__)
print(torchvision.__version__)

try:
	model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
	model.eval()
	x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
	predictions = model(x)

except Exception as ex:
	logging.exception("Error!")
```

**Output:** 
1.1.0
0.3.0
ERROR:root:Error!

> Traceback (most recent call last):
>   File "sample_detection.py", line 12, in <module>
>     predictions = model(x)
>   File "/home/ricardo/miniconda3/envs/CORSMAL/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/ricardo/miniconda3/envs/CORSMAL/lib/python2.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
>     images, targets = self.transform(images, targets)
>   File "/home/ricardo/miniconda3/envs/CORSMAL/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/ricardo/miniconda3/envs/CORSMAL/lib/python2.7/site-packages/torchvision/models/detection/transform.py", line 45, in forward
>     images = self.batch_images(images)
>   File "/home/ricardo/miniconda3/envs/CORSMAL/lib/python2.7/site-packages/torchvision/models/detection/transform.py", line 101, in batch_images
>     pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
> RuntimeError: The expanded size of the tensor (1056) must match the existing size (1066) at non-singleton dimension 2.  Target sizes: [3, 800, 1056].  Tensor sizes: [3, 800, 1066]
>

**Comment by fmassa** [comment] 2019-06-17 11:19
I believe this problem is only present in Python2, and has been fixed in master in https://github.com/pytorch/vision/pull/960

Can you try applying this patch in your version?

**Comment by fmassa** [comment] 2019-06-17 11:20
This indeed looks like a duplicate of https://github.com/pytorch/vision/issues/959, and has been fixed in #959

**Comment by buoyancy99** [comment] 2019-06-17 18:03
> I believe this problem is only present in Python2, and has been fixed in master in #960
> 
> Can you try applying this patch in your version?

This presents in python3 as well

**Comment by fmassa** [comment] 2019-06-17 21:24
@buoyancy99 @RiSaMa I've just tried on my install of torchvision, using Python3 and latest master, and everything works fine for the aforementined example

![image](https://user-images.githubusercontent.com/9110200/59637800-97193900-914e-11e9-8c79-91783913ee71.png)

(including my missing `import torch` line :-) )

**Comment by fmassa** [comment] 2019-06-19 09:23
I believe this has been fixed in the current torchvision master.

Please let me know if this is not the case, but I couldn't reproduce it with my install.

**Closed by fmassa** 2019-06-19 09:23 UTC
Labels: duplicate, module: models, topic: object detection
