### ISSUE TITLE
transforms.functional.rotate doesn't work for grayscale images

### ISSUE THREAD

**Issue by qfgaohao** [pytorch/vision#1776] opened 2020-01-20 03:22 UTC
When applying the function on grayscale images, it throws the following error:   

 packages/torchvision/transforms/functional.py", line 729, in rotate
    return img.rotate(angle, resample, expand, center, fillcolor=fill)
  File "/home/xxx/local/anaconda3/envs/th/lib/python3.7/site-packages/PIL/Image.py", line 2023, in rotate
return self.transform((w, h), AFFINE, matrix, resample, fillcolor=fillcolor)
  File "/home/xxx/local/anaconda3/envs/th/lib/python3.7/site-packages/PIL/Image.py", line 2337, in transform
   im = new(self.mode, size, fillcolor)
  File "/home/xxx/local/anaconda3/envs/th/lib/python3.7/site-packages/PIL/Image.py", line 2544, in new
    return im._new(core.fill(mode, size, color))
 TypeError: function takes exactly 1 argument (3 given)

It is related to the pull request #1280

**Comment by pmeier** [comment] 2020-01-20 10:28
Duplicate of #1759

**Comment by rgommers** [comment] 2020-07-15 10:17
This was fixed, closing. Thanks for the report @qfgaohao and for the fix @pmeier.

**Closed by rgommers** 2020-07-15 10:17 UTC
