### ISSUE TITLE
Error when create_feature_extractor in AlexNet

### ISSUE THREAD

**Issue by githwd2016** [pytorch/vision#6249] opened 2022-07-08 09:28 UTC
### 🐛 Describe the bug

When I try to obtain the feature of layer "classifier.4" in AlexNet, the program has reported an error. The code is as follows:
```
import torch
from torchvision.models import alexnet, AlexNet_Weights
from torchvision.models.feature_extraction import create_feature_extractor

model = alexnet(weights=AlexNet_Weights.IMAGENET1K_V1)
extractor = create_feature_extractor(model, {'classifier.4': 'feat'})
img = torch.rand(3,224,224)
out = extractor(img)
```

**Error message**
```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x36 and 9216x4096)
```

I guess it is because that the shape of output from "flatten" of AlexNet is 256x36 rather than 9216.

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.55
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090
GPU 6: NVIDIA GeForce RTX 3090
GPU 7: NVIDIA GeForce RTX 3090

Nvidia driver version: 510.73.08
cuDNN version: Probably one of the following:
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0+cu116
[pip3] torchmetrics==0.9.1
[pip3] torchtext==0.12.0
[pip3] torchvision==0.13.0+cu116
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.22.3           py39he7a7128_0    defaults
[conda] numpy-base                1.22.3           py39hf524024_0    defaults
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.12.0+cu116             pypi_0    pypi
[conda] torchmetrics              0.9.1                    pypi_0    pypi
[conda] torchtext                 0.12.0                     py39    pytorch
[conda] torchvision               0.13.0+cu116             pypi_0    pypi
```

cc @datumbox

**Comment by datumbox** [comment] 2022-07-08 09:52
@githwd2016 Thans for reporting.

The problem is you are throwing in a single image while the model expects a batch. Replace what you have with the following and it will work:
```
img = torch.rand(1, 3,224,224)
``

To confirm this is the case, remove completely the `create_feature_extractor` from your script and pass the image to the original model. If you do that, you will get the same error.

I believe this should solve your problem so I'll close the issue. If you continue facing problems feel free to reopen.

**Closed as completed by datumbox** 2022-07-08 09:52 UTC
Labels: question, module: models, topic: feature extraction
