### ISSUE TITLE
densenet memory error

### ISSUE THREAD

**Issue by chencodeX** [pytorch/vision#219] opened 2017-08-02 07:57 UTC
I use your densenet.py file to generate a pre-training network, but the network training process will increase over time, the use of GPU memory is also increasing, until the OOM.Why is this?

**Comment by alykhantejani** [comment] 2017-09-03 16:27
Hi @chencodeX I can't see anything obviously wrong in the densenet model, perhaps you are hanging on to tensors in your training loop. Would you be able to post a minimum working example showing this behavior?

**Comment by chencodeX** [comment] 2017-09-04 04:07
it's ok! 
    def forward(self, x):
        x[:, 0] = (x[:, 0] - 0.485) / 0.229
        x[:, 1] = (x[:, 1] - 0.456) / 0.224
        x[:, 2] = (x[:, 2] - 0.406) / 0.225
        features = self.features(x)
        # temp_size = features.size(0)
        out = F.relu(features, inplace=True)
        out = F.avg_pool2d(out, kernel_size=7).view(features.size(0), -1)
        out = self.classifier(out)
        return out
I made a little change to your code and typed the data for an operation.
Now I already know how to fix this problem, I added a line of code:
        x = x.clone()

like this:
    def forward(self, x):
        x = x.clone()
        x[:, 0] = (x[:, 0] - 0.485) / 0.229
        x[:, 1] = (x[:, 1] - 0.456) / 0.224
        x[:, 2] = (x[:, 2] - 0.406) / 0.225
        features = self.features(x)
        # temp_size = features.size(0)
        out = F.relu(features, inplace=True)
        out = F.avg_pool2d(out, kernel_size=7).view(features.size(0), -1)
        out = self.classifier(out)
        return out

This ensures that the cache space occupied by the input data is released.
I really recommend that you also add such a line to the original model code.

**Comment by fmassa** [comment] 2017-09-04 11:55
Is this a problem specific to densenet? I wonder if you are not hitting an issue similar to https://github.com/pytorch/pytorch/issues/839, which was solved long ago. What is your pytorch version?
```python
print(torch.__version__)
```

**Comment by chencodeX** [comment] 2017-09-06 02:18
I was the latest version of pytorch installed in August

**Comment by alykhantejani** [comment] 2017-10-01 17:21
@chencodeX I can't reproduce this bug and can't see anything obviously wrong in the forward code you posted (although the forward code above is not the forward code of densenet).

Is this still an issue for you or did you find a leak elsewhere in your training loop?

**Comment by chencodeX** [comment] 2017-10-12 01:21
Yes, I am in the process of training program GPU memory found in increasing until overflow.

**Comment by alykhantejani** [comment] 2017-10-13 23:02
@chencodeX is the memory increase due to something else in your training loop. It doesn't seem like it's due to the densenet model as far as I can tell? 

Can you pose a minimum working example exhibiting this increase in memory, and perhaps that will help us figure out what the issue is

**Comment by chencodeX** [comment] 2017-10-17 03:13
I am sorry, because the server exception, the previous data and the code has been lost, I tried to reproduce the situation today, but the network is working properly, there is no increase in GPU memory situation.

**Comment by alykhantejani** [comment] 2017-10-17 09:27
Ok, closing this for now then. Please open another issue if you can reproduce in the future :)

**Closed by alykhantejani** 2017-10-17 09:27 UTC
Labels: needs reproduction
