### ISSUE TITLE
MNIST Dataset unavailable

### ISSUE THREAD

**Issue by ydaiming** [pytorch/vision#3573] opened 2021-03-15 16:53 UTC
## 🐛 Bug

When I tried to run [pytorch/examples/mnist/](https://github.com/pytorch/examples/blob/master/mnist/main.py) as an integration test, I got the following HTTP error. I traced down and found the url in `torchvision` instead of `examples`, and when I tried to open the target `http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz`, it also showed up service unavailable on my browser.

```
root@9581d9512697:/examples# python mnist/main.py 2>&1
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "mnist/main.py", line 137, in <module>
    main()
  File "mnist/main.py", line 117, in main
    transform=transform)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 146, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 314, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 140, in download_url
    raise e
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 132, in download_url
    _urlretrieve(url, fpath)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 29, in _urlretrieve
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": USER_AGENT})) as response:
  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

## To Reproduce

    1  git clone https://github.com/pytorch/examples.git
    2  pip uninstall torch torchvision
    3  pip install torch torchvision
    4  cd examples/
    5  python mnist/main.py 2>&1

## Expected behavior

Download the dataset, and run the example mnist successfully.

## Environment

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] sagemaker-pytorch-training==2.4.0
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] mkl                       2020.2                      256    anaconda
[conda] mkl-include               2020.2                      256    anaconda
[conda] numpy                     1.19.1           py36h30dfecb_0    anaconda
[conda] numpy-base                1.19.1           py36h75fe3a5_0    anaconda
[conda] sagemaker-pytorch-training 2.4.0                    pypi_0    pypi
[conda] torch                     1.8.0                    pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi

**Comment by pmeier** [comment] 2021-03-15 17:27
Duplicate of #3549.

**Closed by pmeier** 2021-03-15 17:27 UTC

**Comment by ydaiming** [comment] 2021-03-15 17:30
@pmeier is there a workaround right now, instead of waiting for 0.9.1?
