### ISSUE TITLE
Video dataset can't instantiate correctly on windows.

### ISSUE THREAD

**Issue by eecn** [pytorch/vision#1623] opened 2019-11-30 10:51 UTC
When I use the UCF101 class to instantiate the ucf-101 dataset, I get an error, the platform is Windows10,and the code is
 `ucf101_train = UCF101(root="./Datasets/UCF-101", annotation_path="./Datasets/UCF101TrainTestSplits-RecognitionTask/ucfTrainTestlist", frames_per_clip=16, train=True)`
return 
`AttributeError: Can't pickle local object 'VideoClips._compute_frame_pts.<locals>.DS'`
Looking forward to someone who can help solve this problem.

**Comment by jamt9000** [comment] 2019-12-08 01:05
This happens because ForkingPickler is used on Windows when launching a DataLoader with multiple workers. A dummy dataset is passed to a `DataLoader` inside `VideoClips`, which is an instance of the `DS` class defined in `_compute_frame_pts`, and instances of locally-defined classes cannot be pickled.

This was also the cause of some test failures in #1229

**Comment by jamt9000** [comment] 2019-12-08 01:55
Should be fixed by #1649 but I have not tested on Windows. The video_utils tests are currently disabled on Windows so there could be other issues.

**Comment by eecn** [comment] 2019-12-09 12:17
@jamt9000 Thank you for the explanation. I hope the project can be adapted to the windows system as soon as possible.

**Closed** 2019-12-10 13:01 UTC

**Comment by fmassa** [comment] 2019-12-10 13:02
#1649 was merged (thanks @jamt9000 !) and this should be fixed now.
