### ISSUE TITLE
Mask RCNN do not support trace on GPU

### ISSUE THREAD

**Issue by hgt312** [pytorch/vision#4158] opened 2021-07-07 13:11 UTC
## To reproduce

```python
...
model = ...
model = model.cuda(
model.eval()

inp = torch.Tensor(data_np).cuda(

with torch.no_grad():
    out = model(inp)
    script_module = do_trace(model, inp)
```
However get:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! ......
```

## Enviroment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 8.0.1 (tags/RELEASE_801/final)
CMake version: version 3.19.6
Libc version: glibc-2.17

Python version: 3.7.10 (default, Jun  4 2021, 14:48:32)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1049-aws-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi

**Comment by NicolasHug** [comment] 2021-07-07 13:13
@hgt312 could you please provide a minimal fully reproducible example? With imports, data, etc. It would be easier to help.

**Comment by hgt312** [comment] 2021-07-07 13:45
> @hgt312 could you please provide a minimal fully reproducible example? With imports, data, etc. It would be easier to help.

Sure.

```python
from tvm.contrib.download import download
import cv2, torch

def process_image(img):
    img = cv2.imread(img).astype("float32")
    img = cv2.resize(img, (300, 300))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = torch.from_numpy(img / 255.0).permute(2, 0, 1).float()
    img = torch.unsqueeze(img, axis=0)

    return img

img = "test_street_small.jpg"
img_url = (
    "https://raw.githubusercontent.com/dmlc/web-data/"
    "master/gluoncv/detection/street_small.jpg"
)
download(img_url, img)

data = process_image(img)
data_np = data.detach().numpy()
data_np = data_np.repeat(2, axis=0)

import numpy as np
import torch
import torchvision

batch_size = 2
image_size = [300, 300]
input_shape = (batch_size, 3, *image_size)

def do_trace(model, inp):
    model_trace = torch.jit.trace(model, inp)
    model_trace.eval()
    return model_trace

def dict_to_tuple(out_dict):
    if "masks" in out_dict.keys():
        return out_dict["boxes"], out_dict["scores"], out_dict["labels"], out_dict["masks"]
    return out_dict["boxes"], out_dict["scores"], out_dict["labels"]

class TraceWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, inp):
        out = self.model(inp)
        results = []
        num_out = len(out)
        for i in range(num_out):
            for j in dict_to_tuple(out[i]):
                results.append(j)
        return results

model_func = torchvision.models.detection.maskrcnn_resnet50_fpn
model = TraceWrapper(model_func(pretrained=True))

model = model.cuda()
model.eval()
inp = torch.Tensor(data_np).cuda()

with torch.no_grad():
    out = model(inp)
    script_module = do_trace(model, inp)
```

**Comment by NicolasHug** [comment] 2021-07-07 13:53
Do you have the same issue without the TraceWrapper?

**Comment by datumbox** [comment] 2021-07-14 14:35
The Object Detection models don't currently support tracing.

**Comment by fmassa** [comment] 2021-09-08 07:58
Hi,

Detection models won't support tracing, only scripting via `torch.jit.script`. This is not something that we plan to change, due to inherent limitations of tracing wrt the complexity of a model like Mask R-CNN (which has native control flow).

As such, I'm closing this issue. Hopefully `torch.jit.script` is going to be enough for your use-case.

**Closed by fmassa** 2021-09-08 07:58 UTC
