### ISSUE TITLE
There is a problem in torchvision.datasets.Kinetics 

### ISSUE THREAD

**Issue by DaBihy** [pytorch/vision#6752] opened 2022-10-12 11:59 UTC
### 🐛 Describe the bug

I’m trying to use [torchvision.datasets.Kinetics](https://pytorch.org/vision/main/generated/torchvision.datasets.Kinetics.html) but I’m getting this Assertion Error.

This is the initialization of the dataset
```
test_dataset = torchvision.datasets.Kinetics(root=root_path, frames_per_clip=33,
     step_between_clips=5, num_workers = 40, split='test', transform = transforms.RandomResizedCrop(size=224))
```
This is error I get:
```
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bairouk/anaconda3/envs/deep/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bairouk/anaconda3/envs/deep/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bairouk/anaconda3/envs/deep/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bairouk/anaconda3/envs/deep/lib/python3.10/site-packages/torchvision/datasets/kinetics.py", line 234, in __getitem__
    video, audio, info, video_idx = self.video_clips.get_clip(idx)
  File "/home/bairouk/anaconda3/envs/deep/lib/python3.10/site-packages/torchvision/datasets/video_utils.py", line 373, in get_clip
    assert len(video) == self.num_frames, f"{video.shape} x {self.num_frames}"
AssertionError: torch.Size([34, 720, 1280, 3]) x 33
```
Thank you.

### Versions

pytorch                   1.11.0
torchvision               0.12.0
python                    3.10.4

cc @pmeier

**Comment by pmeier** [comment] 2022-10-12 12:20
That seems more related to the

https://github.com/pytorch/vision/blob/7d36d263a8356fac0bb363617b0c57c3bac6f89f/torchvision/datasets/video_utils.py#L73

object than the dataset itself. @YosuaMichael / @jdsgomes / @bjuncek could one of you have a look?

**Comment by YosuaMichael** [comment] 2022-10-13 21:38
@DaBihy I tried to build the same kinetics test dataset and iterate some samples, but I can't reproduce the error.

Do you know which exact video that cause the problem? This would help us to check more detail and try to reproduce the error.

**Comment by DaBihy** [comment] 2022-10-14 09:06
@YosuaMichael This is some of the videos that cause the error. they work just fine when I play them on a media player.
yaoNwz99xM_000062_000072.mp4
3caPS4FHFF8_000036_000046.mp4
0wR5jVB-WPk_000417_000427.mp4
3yaoNwz99xM_000062_000072.mp4
0wR5jVB-WPk_000417_000427.mp4
Thank you.

**Comment by YosuaMichael** [comment] 2022-10-14 12:24
Thanks for sharing the video @DaBihy , I confirm I can reproduce the same error on those video with torchvision 0.12.0.
When I run the same script on latest torchvision 0.13.0, the error gone, so I guess this probably has been fixed.

@DaBihy I suggest you to update the torchvision version and see if that fix the issue.
I think this should fix the issue so I will close this, but if you still get the problem, feel free to reopen this issue.

**Closed by YosuaMichael** 2022-10-14 12:24 UTC
Labels: module: datasets, module: video

**Comment by DaBihy** [comment] 2022-10-15 15:08
@YosuaMichael  Thank you for the rapid answer. the latest version does not have the bug.
On the other hand ```torchvision.datasets.Kinetics``` doesn't have a function to resize audio which causes the following error ```RuntimeError: stack expects each tensor to be equal size, but got [2, 31744] at entry 0 and [2, 32149] at entry 1```. It's normal to have such an error because ```default_collate``` can't stack audio with different sizes. Anyway, in my case, I don't need audio so I eliminated it using a custom ```collate_fn``. It would be great if you added a function for audio transform 
thank you again @YosuaMichael @pmeier

**Comment by pmeier** [comment] 2022-10-17 05:43
> It would be great if you added a function for audio transform thank you again

We won't given that this is out of scope for a vision library that we are. If you need the audio for something, you should have a look at [`torchaudio`](https://github.com/pytorch/audio) that specializes in these things.

> Anyway, in my case, I don't need audio so I eliminated it using a custom `collate_fn`.

That is what we also do:

https://github.com/pytorch/vision/blob/f467349ce0d41c23695538add22f6fec5a30ece4/references/video_classification/train.py#L129-L132

(`d[1]` is the audio)
