### ISSUE TITLE
UserWarning: video_reader video backend is not available

### ISSUE THREAD

**Issue by fepegar** [pytorch/vision#2216] opened 2020-05-14 18:28 UTC
## 🐛 Bug

I get a "`video_reader` video backend is not available" warning when trying to set it.

## To Reproduce

```shell
$ conda create -n tv python -y && conda activate tv
$ pip install numpy                                                                                               
$ pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
$ python -c "import torchvision; torchvision.set_video_backend('video_reader')"
````

Output:

```python-traceback
[('__call__', <function LevelMapper.__call__ at 0x123462820>), ('__init__', <function LevelMapper.__init__ at 0x123462790>)]
[('__call__', <function BalancedPositiveNegativeSampler.__call__ at 0x123649280>), ('__init__', <function BalancedPositiveNegativeSampler.__init__ at 0x1236491f0>)]
[('__init__', <function BoxCoder.__init__ at 0x123657af0>), ('decode', <function BoxCoder.decode at 0x123657ca0>), ('decode_single', <function BoxCoder.decode_single at 0x123657d30>), ('encode', <function BoxCoder.encode at 0x123657b80>), ('encode_single', <function BoxCoder.encode_single at 0x123657c10>)]
[('__call__', <function Matcher.__call__ at 0x1234628b0>), ('__init__', <function Matcher.__init__ at 0x123649160>), ('set_low_quality_matches_', <function Matcher.set_low_quality_matches_ at 0x123462700>)]
[('__init__', <function ImageList.__init__ at 0x123657e50>), ('to', <function ImageList.to at 0x123657a60>)]
[('__init__', <function Timebase.__init__ at 0x123b8cca0>)]
[('__init__', <function VideoMetaData.__init__ at 0x123b8ce50>)]
/usr/local/Caskroom/miniconda/base/envs/tv/lib/python3.8/site-packages/torchvision/__init__.py:65: UserWarning: video_reader video backend is not available
  warnings.warn("video_reader video backend is not available")
```

I'm using the nightly version because I hoped this would be fixed in #2183.

I get only the warning (i.e. last two lines) in the stable pip release.

## Expected behavior

No warning when I set the backend.

## Environment

PyTorch version: 1.6.0.dev20200514
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.17.2

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.4
[pip] torch==1.6.0.dev20200514
[pip] torchvision==0.7.0.dev20200514
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.6.0.dev20200514          pypi_0    pypi
[conda] torchvision               0.7.0.dev20200514          pypi_0    pypi

## Additional context

Discovered when I tried following @bjuncek advice in #1884.

**Comment by fmassa** [comment] 2020-05-15 12:53
Hi,

This is expected, as we don't ship `video_reader` backend in the pre-compiled binaries.
For enabling `video_reader`, you'll need to compile torchvision from source following the "From source" section in https://github.com/pytorch/vision#installation

Note that it will require `ffmpeg` installed in your system for the `video_reader` to be available. You can obtain it by installing pyav from conda.

As such, I'm closing this issue but let us know if you have issues compiling torchvision from source.

**Closed by fmassa** 2020-05-15 12:53 UTC

**Comment by fepegar** [comment] 2020-05-15 13:20
I'll try building.

> This is expected, as we don't ship video_reader backend in the pre-compiled binaries.

Is this documented anywhere?

**Comment by fepegar** [comment] 2020-05-15 14:13
Got this after building from source and running the command I mentioned above.

```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/vision/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/private/tmp/vision/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/private/tmp/vision/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/private/tmp/vision/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/private/tmp/vision/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/private/tmp/vision/torchvision/ops/boxes.py", line 8, in <module>
    def nms(boxes, scores, iou_threshold):
  File "/usr/local/Caskroom/miniconda/base/envs/tv/lib/python3.8/site-packages/torch/jit/__init__.py", line 1290, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
object has no attribute nms:
  File "/private/tmp/vision/torchvision/ops/boxes.py", line 41
        by NMS, sorted in decreasing order of scores
    """
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

Here's my environment:
```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.17.2

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.4
[pip] torch==1.5.0
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.5.0                    pypi_0    pypi
```

**Comment by fmassa** [comment] 2020-05-15 15:06
@fepegar 
> Is this documented anywhere?

it is explained in the release notes https://github.com/pytorch/vision/releases/tag/v0.4.2 but maybe we can make it more explicit in the error message

About the error you got, looks like the compilation didn't succeed properly (you might have had error messages showing up).
I would suggest first uninstalling torchvision and then re-compiling it from source.

**Comment by fepegar** [comment] 2020-05-15 16:43
> maybe we can make it more explicit in the error message

Let me know if there's anything I can do to help.

> I would suggest first uninstalling torchvision and then re-compiling it from source.

I compiled it from source in a fresh environment.

> looks like the compilation didn't succeed properly (you might have had error messages showing up).

You're right. I'll see if there are issues about that and, if not, I'll create one.

**Comment by fmassa** [comment] 2020-05-18 12:56
@fepegar if you could send a PR modifying the error message with `video_reader` backend mentioning that you need to compile torchvision from source to get it, it would be great!

**Comment by fepegar** [comment] 2020-05-18 12:58
Ok, I will! But should I wait until #2220 is resolved?

**Comment by fmassa** [comment] 2020-05-18 12:58
I'm looking at #2220 now, and I think I reproduced the error

**Comment by fmassa** [comment] 2020-05-18 12:59
@fepegar you can send the PR improving the error message right now as it's independent on #2220 being fixed or not

**Comment by JuanFMontesinos** [comment] 2020-07-24 22:37
Hi, I was digging into video_reader backend and this may be interesting https://github.com/pytorch/vision/issues/2490

**Comment by Droid021** [comment] 2020-12-25 22:41
Hi, just an addition to this, Compiling torchvision requires a nightly version of PyTorch, this should be in the readme (took me a few to figure out why the compilation was failing).
