### ISSUE TITLE
Downloading pre-trained models to a custom path(which I prefer to), instead of a fixed one

### ISSUE THREAD

**Issue by Sean16SYSU** [pytorch/vision#2299] opened 2020-06-08 08:37 UTC
## 🚀 Feature

When using the pre-trained models with `pretrained=True`, I find no way to input my custom path for downloading or loading models.

I have read the source codes in my local version of `torchvision` and the latest code in github, and found no way to input the self-defined path for downloading or loading, both.

## Motivation

Well, there is no bug in the source codes(for the very design) of any versions. And I am sure that everything works well even without the design I requested. However, I still feel a bit unaccustomed and inflexible while using it, because I always want to arrange the downloading files in my PC.

BTW, I thinking it easy to implement.

## Pitch

a new parameter like `model_path=None` is added to the models or functions.

## Alternatives

same as `Pitch`

**Comment by fmassa** [comment] 2020-06-08 10:18
Hi,

Thanks for opening this issue.

This has been requested in the past, see https://github.com/pytorch/vision/issues/616, and there is an open PR for it in https://github.com/pytorch/vision/pull/653

I still think that using `TORCH_HOME` (or `TORCH_MODEL_ZOO` which is deprecated) https://github.com/pytorch/vision/pull/624 is the preferred way to do it, as it makes your code be agnostic to paths, and it can be controlled by an env var.

As such, I'm closing this issue as duplicate of https://github.com/pytorch/vision/issues/616, but please feel free to continue the discussion in the linked issue.

**Closed by fmassa** 2020-06-08 10:18 UTC
