### ISSUE TITLE
unable to load inception model. Or any other architect other than alexnet

### ISSUE THREAD

**Issue by richesh09** [pytorch/vision#1592] opened 2019-11-18 07:30 UTC
import torchvision.models.inception

# works fine
arch = torchMd.alexnet(pretrained=True)

# gives error, also tried vgg, densenet
arch = torchMd.inception(pretrained=True)

AttributeError                            Traceback (most recent call last)
<ipython-input-43-3882461a2f37> in <module>
----> 1 print(torchvision.__version__)

AttributeError: module 'torchvision' has no attribute '__version__'

**Comment by richesh09** [comment] 2019-11-18 07:49
# on trying inception_v3
arch = torchMd.inception_v3(pretrained=True)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-55-2cf9d6b9f771> in <module>
----> 1 arch = torchMd.inception_v3(pretrained=True)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/inception.py in inception_v3(pretrained, **kwargs)
     24         if 'transform_input' not in kwargs:
     25             kwargs['transform_input'] = True
---> 26         model = Inception3(**kwargs)
     27         model.load_state_dict(model_zoo.load_url(model_urls['inception_v3_google']))
     28         return model

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/inception.py in __init__(self, num_classes, aux_logits, transform_input)
     63                 X = stats.truncnorm(-2, 2, scale=stddev)
     64                 values = torch.Tensor(X.rvs(m.weight.data.numel()))
---> 65                 m.weight.data.copy_(values)
     66             elif isinstance(m, nn.BatchNorm2d):
     67                 m.weight.data.fill_(1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (864) at non-singleton dimension 3

**Comment by pmeier** [comment] 2019-11-18 10:44
Without any information about what versions you are using, it is hard to help you. Could you please paste the following snippet into your python console and post the output here:

```python
import torch
print(torch.__version__)
import torchvision
print(torchvision.__version__)
```

**Comment by richesh09** [comment] 2019-11-18 12:07
1.3.1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-75-387f9cd332b1> in <module>
      2 print(torch.__version__)
      3 import torchvision
----> 4 print(torchvision.__version__)

AttributeError: module 'torchvision' has no attribute '__version__'



However, I have installed dependencies as recently as last week, so torchvision has to be latest
Further please find the exact code-lines which are giving me error


import torchvision.models as torchMd

######## Working fine. Even their other versions too like vgg11_bn, 16 etc, however vgg itself giving error.
###### densenet neither densenet nor densenet 161, 169, 201 working
#arch = torchMd.alexnet(pretrained=True)
#arch = torchMd.resnet101(pretrained=True)
#arch = torchMd.squeezenet1_0(pretrained=True)
#arch = torchMd.vgg11(pretrained=True)


###### these all are giving error mentioned below
#arch = torchMd.inception()
#arch = torchMd.densenet()
#arch = torchMd.densenet201()
#arch = torchMd.resnet(pretrained=True)
#arch = torchMd.squeezenet(pretrained=True)
#arch = torchMd.vgg(pretrained=True)
#arch = torchMd.densenet(pretrained=True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-100-e415919d41ef> in <module>
     10 #arch = torchMd.resnet(pretrained=True)
     11 #arch = torchMd.squeezenet(pretrained=True)
---> 12 arch = torchMd.vgg(pretrained=True)
     13 #arch = torchMd.densenet(pretrained=True)

TypeError: 'module' object is not callable


##### in case of densenet161, 169, 201 error message is as follows
arch = torchMd.densenet201()

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-101-7f46aa25aaa3> in <module>
     12 #arch = torchMd.inception()
     13 #arch = torchMd.densenet()
---> 14 arch = torchMd.densenet201()
     15 #arch = torchMd.resnet(pretrained=True)
     16 #arch = torchMd.squeezenet(pretrained=True)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/densenet.py in densenet201(pretrained, **kwargs)
     52     """
     53     model = DenseNet(num_init_features=64, growth_rate=32, block_config=(6, 12, 48, 32),
---> 54                      **kwargs)
     55     if pretrained:
     56         model.load_state_dict(model_zoo.load_url(model_urls['densenet201']))

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/densenet.py in __init__(self, growth_rate, block_config, num_init_features, bn_size, drop_rate, num_classes)
    140         for i, num_layers in enumerate(block_config):
    141             block = _DenseBlock(num_layers=num_layers, num_input_features=num_features,
--> 142                                 bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
    143             self.features.add_module('denseblock%d' % (i + 1), block)
    144             num_features = num_features + num_layers * growth_rate

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/densenet.py in __init__(self, num_layers, num_input_features, bn_size, growth_rate, drop_rate)
     96         super(_DenseBlock, self).__init__()
     97         for i in range(num_layers):
---> 98             layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
     99             self.add_module('denselayer%d' % (i + 1), layer)
    100 

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision/models/densenet.py in __init__(self, num_input_features, growth_rate, bn_size, drop_rate)
     75     def __init__(self, num_input_features, growth_rate, bn_size, drop_rate):
     76         super(_DenseLayer, self).__init__()
---> 77         self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
     78         self.add_module('relu.1', nn.ReLU(inplace=True)),
     79         self.add_module('conv.1', nn.Conv2d(num_input_features, bn_size *

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in add_module(self, name, module)
    193             raise KeyError("attribute '{}' already exists".format(name))
    194         elif '.' in name:
--> 195             raise KeyError("module name can't contain \".\"")
    196         elif name == '':
    197             raise KeyError("module name can't be empty string \"\"")

KeyError: 'module name can\'t contain "."'

**Comment by richesh09** [comment] 2019-11-18 15:07
Hi,
Regarding version detail, I might have made an error so will check it tomorrow. However regarding model, my concern is mainly for inception model as I intend to train my data on it. Can you please share your insights for the same.

**Comment by pmeier** [comment] 2019-11-18 15:34
This is the same case as 2. in my previous comment:

```python
import torchvision.models as torchMd
arch = torchMd.inception(pretrained=True)
```

is not going to work, since `torchMd.inception` points to module (that means an actual file with a .py extension) rather than a function, which is of course not callable. Thus, the error reads:

```
TypeError: 'module' object is not callable
```

This is working for `alexnet`, because the function to load `AlexNet` has the same name as the module. This is not working for the other cases you described, since the functions are named differently than the module.

---

As of now the only `Inception` model implemented in PyTorch is `inception_v3`. To load it you can use

```python
import torchvision.models as torchMd
arch = torchMd.inception_v3()
```

**Comment by fmassa** [comment] 2019-11-18 16:07
I believe @pmeier has addressed all the concerns from @richesh09 .

As such, I'm closing this issue, but please let me know if this isn't the case.

**Comment by fmassa** [comment] 2019-11-18 16:07
And thanks @pmeier for all the help!

**Closed by fmassa** 2019-11-18 16:07 UTC
Labels: awaiting response, module: models, question

**Comment by richesh09** [comment] 2019-11-18 16:26
Hi 
I got your point. Anyhow for case of arch= torchMd.inception_v3() is throwing me error with error message mentioned in my comment 2. Can you please have a look at it too

**Comment by pmeier** [comment] 2019-11-18 16:30
Without knowing the exact `torch` and `torchvision` versions, further help is nothing more than guessing. Please provide this information first. Otherwise we are unable to help you. As I mentioned before, this working on my setup with the current stable releases.

**Comment by richesh09** [comment] 2019-11-19 05:32
Hi @pmeier ,
Please note that I just retired and the error message for torchvision remains same.

import torch
print(torch.__version__)
import torchvision
print(torchvision.__version__)

1.3.1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-387f9cd332b1> in <module>
      2 print(torch.__version__)
      3 import torchvision
----> 4 print(torchvision.__version__)

AttributeError: module 'torchvision' has no attribute '__version__'

however I am having a folder named "torchvision-0.1.9.dist-info" in my working environment.

**Comment by pmeier** [comment] 2019-11-19 07:51
`torchvision==0.1.9` is a very old release. The last commit was in August 2017. Thus, this is not compatible with the current `torch==1.3.1` release. Updating to `torchvision==0.4.2` should solve your problem.

**Comment by richesh09** [comment] 2019-11-19 09:14
Thanks. It worked on updating.

**Comment by pmeier** [comment] 2019-11-19 09:23
Without being snarky:

Please just follow the instructions we are giving you, if you want us to help you. This whole issue could have been resolved far earlier, if you simply posted your versions in the first place or at least after I asked you too.

For the future:

Since the models are an integral part of `torchvision`, if a bug like you described existed, most likely you are not alone reporting it. Since no one else reported something similar, a good first step is to update your packages to the newest releases and see if the issue is already resolved. If you are for whatever reason stuck on a specific version for `torch` or `torchvision`, make sure to include them in the bug report. Doing so makes debugging your problem far easier for us.
