### ISSUE TITLE
python setup.py install caused the error: ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by terU3760** [pytorch/vision#3043] opened 2020-11-23 15:42 UTC
## To Reproduce

1. install pytorch-nightly
2. git clone https://github.com/pytorch/vision.git
3. in the vision folder, type: python setup.py install

## Expected behavior

Successfully installed torch vision

## Environment

 - Ubuntu 16.04:
 - try to install torch vision from source 
 - python setup.py install
 - CUDA 9.0/cuDNN versionv7.4
 - GTX 1080

**Comment by vfdev-5** [comment] 2020-11-25 17:23
@terU3760 couldn't reproduce your issue in docker ubuntu 16.04 with python 3.8.5 installed using conda. Please, provide more details.

**Comment by terU3760** [comment] 2020-11-27 12:35
I just followed an instruction,
I have already changed python3.8 to python3,6.7
First run ...... and
conda install pytorch-nightly cudatoolkit=9.0 -c pytorch
and then
git clone https://github.com/pytorch/vision.git
and then
in the vision folder, type: python setup.py install
then reported the error:
ModuleNotFoundError: No module named 'torch'

Factually when I have finshed run the following installation:
conda install pytorch-nightly cudatoolkit=9.0 -c pytorch
I started python
and typed:
import torch
It also reported the error:
ModuleNotFoundError: No module named 'torch'

**Comment by terU3760** [comment] 2020-11-27 12:40
Sorry, I have found the cause!
I have misused the environment!
Sorry to have bothered you all and wasted your time!

**Comment by vfdev-5** [comment] 2020-11-27 13:46
@terU3760 great that you could find the issue. Let me close the issue as resolved.

Please, note that installing pytorch-nightly is done like 
```diff
- conda install pytorch-nightly cudatoolkit=9.0 -c pytorch
+ conda install pytorch cudatoolkit=9.0 -c pytorch-nightly
```

**Closed by vfdev-5** 2020-11-27 13:46 UTC
Labels: needs reproduction, topic: build
