### ISSUE TITLE
pyinstaller interaction with torchvision

### ISSUE THREAD

**Issue by SangbumChoi** [pytorch/vision#1899] opened 2020-02-19 04:39 UTC
Setting: torchvision 0.5.0
When compile with torchvision 0.5.0 it has an error comming with 
File "site-packages \ torchvision \ ops \ misc.py", line 135, in <module>
  
File "site-packages \ torchvision \ ops \ misc.py", line 148, in FrozenBatchNorm2d
  
File "site-packages \ torch \ jit \ __ init__.py ", line 1204, in script_method
  
File" site-packages \ torch \ jit \ frontend.py ", line 156, in get_jit_def
File" inspect.py ", line 955, in getsourcelines
  
File" inspect .py ", line 786, in findsource

OSError: could not get source code

but most of the library requires version newer than 0.2.2 which is not basic solution @ # #

-

**Comment by SangbumChoi** [comment] 2020-02-19 05:30
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/34004152/74804720-5e0c1680-5324-11ea-8974-ce18e0692b42.png">
this is the exact error that pops up

**Comment by anhoangphuc** [comment] 2020-02-24 15:20
I have the same error in ubuntu 18.04. :'(

**Comment by SangbumChoi** [comment] 2020-02-27 07:28
@anhoangphuc uploading your code status will also help solving this problem

**Comment by Sstrap** [comment] 2020-03-10 16:59
Got the same error in ubuntu 16.04, do you have any update, thoughts or solution on this ?

**Comment by SangbumChoi** [comment] 2020-03-10 22:55
@Sstrap Some suggestion on online offers to downgrade torchvision to 0.2.2 however my current version is 0.5.0 and need some utils in order to run my python script so at this moment I couldn't find any solution for this.

**Comment by borijang** [comment] 2020-03-11 09:10
Had the same problem on Windows 10. 
I didn't manage to solve it, but I can confirm that it works when downgrading torchvision to 0.2.2.

**Comment by fmassa** [comment] 2020-03-11 13:25
@SangbumChoi since the 0.5.0 release of torchvision, we don't use `@torch.jit.script` in `FrozenBatchNorm` anymore, but other parts of the code still use it.

I don't have any experience with pyinstaller, so I would expect that it might be better to open an issue in pyinstaller reporting the issue. There might be a flag that you can pass to pyinstaller to make it work with torchvision, but I'm not aware of it.

**Comment by Sstrap** [comment] 2020-03-11 13:41
FYI, I opened an issue on PyInstaller (https://github.com/pyinstaller/pyinstaller/issues/4740#issue-578771079).
The only workaround I found to make things work was to downgrade to torchvision 0.2.2 and manually add the code I needed. This is clearly a dirty solution, hopefully I will find something better in the future.

**Comment by Sstrap** [comment] 2020-03-12 13:59
Here are the workarounds I found to make things work.

### Solution 1: patch torchvision 0.2.2 (dirty and painful)
Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).

### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit.
Simply add this path at the beginning of your entry point:
```
def script_method(fn, _rcb=None):
    return fn
def script(obj, optimize=True, _frames_up=0, _rcb=None):
    return obj    
import torch.jit
torch.jit.script_method = script_method 
torch.jit.script = script
```


I still think there should be a more direct way to do that with pyinstaller, but this works for me.
I hope it will help others too.

**Comment by SangbumChoi** [comment] 2020-03-15 03:06
@Sstrap I will try second one and tell if it is work

**Comment by Ed-Roodzant** [comment] 2020-05-07 20:08
Having this same problem.  Not 100% sure where to put that patch, but not having any success yet.

**Comment by windspirit95** [comment] 2020-06-15 06:27
> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit.
> Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me.
> I hope it will help others too.

Solution 2 worked for me. Thanks.
A more detailed solution could be as:
- Adding above code to the beginning of your main program
- Adding the files/packages you need in a.datas in .spec file, as well as hidden_import (just for sure :)), for example:
datas=[(path.join(site_packages,"av"), "av"),
					(path.join(site_packages,"fvcore"), "fvcore"),
					(path.join(site_packages,"torch"), "torch"),
					(path.join(site_packages,"torchvision"), "torchvision"),
					('D:/detectron2_repo', "detectron2")],
             hiddenimports=['av', 'fvcore', 'torch', 'torchvision', 'detectron2'],

**Comment by fmassa** [comment] 2020-07-03 09:32
Hi,

We have now hopefully fix this issue by replacing instances of `@torch.jit.script` with `@torch.jit._script_if_tracing`, and this fix will be present in the next release of torchvision, which will be out in a few weeks.

As such, I'm closing this issue as I believe this should be fixed with the 0.7.0 release, but please let us know if this isn't fixed when the 0.7.0 release comes out

**Closed by fmassa** 2020-07-03 09:32 UTC
Labels: topic: binaries

**Comment by chiminhle** [comment] 2021-04-13 05:44
> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit.
> Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me.
> I hope it will help others too.

Solution 2 worked for me. Thank you very much <3

**Comment by super233** [comment] 2021-05-10 03:50
> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit.
> Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me.
> I hope it will help others too.

It's useful, save my days, thanks!

**Comment by fmassa** [comment] 2021-05-10 13:02
@super233 are you still facing those issues even with latest torchvision?

**Comment by super233** [comment] 2021-05-10 13:22
> @super233 are you still facing those issues even with latest torchvision?

No, my torchvision version is 0.5.

**Comment by shuosure** [comment] 2022-01-23 14:28
next

> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit. Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me. I hope it will help others too.

then next,I encounter “ File "torch\_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::_cuda_version”
can have any idear？

**Comment by monsieurpooh** [comment] 2022-02-02 12:37
> 

This would've worked perfeclty if not for the fact that it completely eliminates the ability to use CUDA and forces CPU.

**Comment by anantgupta129** [comment] 2022-03-27 14:53
> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit. Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me. I hope it will help others too.

can you share the full spec file i am not sure where to add it

**Comment by Mindtrip-Inno** [comment] 2022-11-20 20:00
@Sstrap  How can i patch like in second example couldn't understand it. Can you please eleborate ? Like to which file torch.jit._script ? of which line

**Comment by swaradgat19** [comment] 2023-06-20 18:11
> Here are the workarounds I found to make things work.
> 
> ### Solution 1: patch torchvision 0.2.2 (dirty and painful)
> Pyinstaller works well with torchvision 0.2.2, thus if you do not use too many functionnalities of more recent version of torchvision, you can "patch" old torchvision 0.2.2 by adding the needed new tools. Note that this may need you first use compiled file of torchvision >= 3.0 (_C.so).
> 
> ### Solution 2: Keep recent torchvision & patch torch.jit in your entry point
> I found some monkey patch on stackoverflow and dev blogs that simply overwrite 2 methods of torch.jit. Simply add this path at the beginning of your entry point:
> 
> ```
> def script_method(fn, _rcb=None):
>     return fn
> def script(obj, optimize=True, _frames_up=0, _rcb=None):
>     return obj    
> import torch.jit
> torch.jit.script_method = script_method 
> torch.jit.script = script
> ```
> 
> I still think there should be a more direct way to do that with pyinstaller, but this works for me. I hope it will help others too.

Could you elaborate on what you mean by "entry point"?
