### ISSUE TITLE
torchvison.io.decode_jpeg memory leaks on GPU while file on CPU

### ISSUE THREAD

**Issue by lincchenl** [pytorch/vision#5103] opened 2021-12-16 02:54 UTC
### 🐛 Describe the bug

When I know torchvision starts to support decoing jpegs with nvjpeg, I was happy to try it but found memory leak when decoding with GPU. Here is my code below:

```
            filename = self.cocoset.loadImgs(index+1)[0]['file_name']
            fullname = join(self.picpath,filename)
            img = io.read_file(fullname)
            img = io.decode_jpeg(img,device=self.device)
            img = img.unsqueeze(0)
```
here self.device='cuda:0'
But I found the usage of graphic card memory increased non-stopping and finally caused an OOM.
I tried the cpu version with:
```
            filename = self.cocoset.loadImgs(index+1)[0]['file_name']
            fullname = join(self.picpath,filename)
            img = io.read_file(fullname)
            img = io.decode_jpeg(img).to(self.device)
            img = img.unsqueeze(0)
```
It worked flawlessly without any abnormal memory usage.

### Versions

I worked on Debian 10 with NVIDIA driver 495.29.05+CUDA 11.5.1(latest).
with AMD 5900X+dual RTX 3090
python3.8+pytorch1.10.1+torchvision 0.11.2+cu113 which installed as the pytorch mainpage guide:

> pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

now I can only put decoding process on cpus,I hope using GPU decoding to accelerate my training process,many thxs!

**Comment by NicolasHug** [comment] 2022-02-25 09:28
Thanks for the report @lincchenl , I think this is a duplicate of https://github.com/pytorch/vision/issues/4378 so I'll close this one. From https://github.com/pytorch/vision/issues/4378#issuecomment-1044957322 , the bug comes from nvjpeg directly, and it seems that it was fixed in CUDA 11.6.

**Closed by NicolasHug** 2022-02-25 09:28 UTC
