### ISSUE TITLE
CelebA dataset error

### ISSUE THREAD

**Issue by Nilanshrajput** [pytorch/vision#2387] opened 2020-07-03 12:15 UTC
## 🐛 Bug

 CelebA Dataset download produce bad zip file

## To Reproduce

`from torchvision.datasets import CelebA
import os
os.mkdir('Data')
liader = CelebA(root = '/Data',download=True)`

## Environment
On google Colab 
Please copy and paste the output from our
`Collecting environment information...
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.1+cu101
[conda] Could not collect`

## Additional context

`---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
<ipython-input-12-1f78590b780f> in <module>()
      2 import os
      3 #os.mkdir('Data')
----> 4 liader = CelebA(root = '/Data',download=True)

3 frames
/usr/lib/python3.6/zipfile.py in _RealGetContents(self)
   1196             raise BadZipFile("File is not a zip file")
   1197         if not endrec:
-> 1198             raise BadZipFile("File is not a zip file")
   1199         if self.debug > 1:
   1200             print(endrec)

BadZipFile: File is not a zip file`

**Comment by fmassa** [comment] 2020-07-03 12:26
Hi,

Thanks for opening this issue! I believe this is a duplicate of https://github.com/pytorch/vision/issues/2317, and should be fixed with https://github.com/pytorch/vision/pull/2321 (which I'll be merging today after a rebase)

**Comment by fmassa** [comment] 2020-07-03 12:26
Closing as a duplicate of  #2317

**Closed by fmassa** 2020-07-03 12:26 UTC

**Comment by Nilanshrajput** [comment] 2020-07-03 12:28
okay, but I was able to download 3 days ago :) on colab

**Comment by fmassa** [comment] 2020-07-03 12:33
yeah, it is a problem with Google Drive exceeding quota. We will be raising a more meaningful error message with #2321
