### ISSUE TITLE
Automated testing discovered that `image::read_png` sometimes can not be initialized on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/vision#4787] opened 2021-10-29 05:36 UTC
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch.github.io/runs/4042987825?check_suite_focus=true
Several Windows configuration tests of torchvision failed with `No such operator image::decode_png`

### Versions

0.11.1

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @mszhanyi

**Comment by malfet** [comment] 2021-10-29 18:07
I've already checked that libjpeg and libpng dlls are included both in variant of the package that succeeded and failed the test:
```
$ python -c "import torchvision;import os;import glob;print(glob.glob(f'{os.path.dirname(torchvision.__file__)}/*.dll'))"
['C:\\tools\\miniconda3\\lib\\site-packages\\torchvision\\libjpeg.dll', 'C:\\tools\\miniconda3\\lib\\site-packages\\torchvision\\libpng16.dll', 'C:\\tools\\miniconda3\\lib\\site-packages\\torchvision\\zlib.dll']
```

**Comment by fmassa** [comment] 2021-10-29 18:12
@andfoy can you try
```
import torch

torch.ops.load_library('path/to/image.so')
```

and see the error message?

**Comment by andfoy** [comment] 2021-11-01 16:37
I tried to reproduce it locally on my Windows machine, but without success. I installed everything from the pytorch-stable url, just like the CIs did. The only guess is that the path collection used by `LoadLibrary` is being modified somehow that those DLLs are not being picked up? 

![imagen](https://user-images.githubusercontent.com/1878982/139707196-34457542-f7be-4865-b26c-d9fce4b6ce1f.png)

**Comment by mszhanyi** [comment] 2021-11-02 05:18
Interesting!
Py3.8 + cu113 works. I verified it locally
https://github.com/pytorch/pytorch.github.io/runs/4042987908?check_suite_focus=true

**Comment by mszhanyi** [comment] 2021-11-02 06:45
> I tried to reproduce it locally on my Windows machine, but without success. I installed everything from the pytorch-stable url, just like the CIs did. The only guess is that the path collection used by `LoadLibrary` is being modified somehow that those DLLs are not being picked up?
> 
> ![imagen](https://user-images.githubusercontent.com/1878982/139707196-34457542-f7be-4865-b26c-d9fce4b6ce1f.png)

@andfoy it could be reproduced in windows CPU machine with cudatoolkit installed.
If your  windows machine has GPUs, you might set CUDA_VISIBLE_DEVICES="" or disable it in device manager.

**Comment by andfoy** [comment] 2021-11-02 19:19
> @andfoy it could be reproduced on windows CPU machine with cudatoolkit installed.

@mszhanyi, was this mixing conda and pip installations?

**Comment by andfoy** [comment] 2021-11-02 19:24
![imagen](https://user-images.githubusercontent.com/1878982/139932574-28b5e727-006a-45d4-a178-8f64fd0c44e1.png)

This was installing PyTorch (CPU) and Torchvision stable using pip:

```batch
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_stable.html
```

**Comment by mszhanyi** [comment] 2021-11-02 23:05
> > @andfoy it could be reproduced on windows CPU machine with cudatoolkit installed.
> 
> @mszhanyi, was this mixing conda and pip installations?

Yes, I reproduced in a conda environment

**Comment by mszhanyi** [comment] 2021-11-02 23:08
> ![imagen](https://user-images.githubusercontent.com/1878982/139932574-28b5e727-006a-45d4-a178-8f64fd0c44e1.png)
> 
> This was installing PyTorch (CPU) and Torchvision stable using pip on Python 3.7:
> 
> ```batchfile
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_stable.html
> ```

@andfoy , You installed a nightly version.
stable version installing command is 
`pip install torch torchvision torchaudio`

try installing a cuda version
`pip install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`

**Comment by mszhanyi** [comment] 2021-11-03 10:11
@malfet @fmassa
I think I might find the root cause.
In python3.7, we have to run `conda install libpng`. But it looks  `conda install libpng` isn't necessary in Py38 or Py39 environment.

So far, I couldn't login GHA machine.  I've verified locally and circle machine.
@malfet , could you ssh in it and run 'conda install libpng' to verify it.

@andfoy , could you try to uninstall libpng in you python3.7 environment.

**Comment by malfet** [comment] 2021-11-03 12:01
@mszhanyi there are no conda environment when this experiment is run on GHA Windows instances. But why installing lipng is necessary only when python-3.7 or cuda-10.2 is used, as it is bundled with all versions of torchvision?

@andfoy and why do we bundle those libraries as dynamic dependencies instead of compiling them in?

**Comment by malfet** [comment] 2021-11-03 12:03
> I tried to reproduce it locally on my Windows machine, but without success. I installed everything from the pytorch-stable url, just like the CIs did. The only guess is that the path collection used by `LoadLibrary` is being modified somehow that those DLLs are not being picked up? 

@andfoy how did you install your python runtime? Via conda or downloaded from Python.org?

**Comment by mszhanyi** [comment] 2021-11-03 14:24
> @mszhanyi there are no conda environment when this experiment is run on GHA Windows instances. But why installing lipng is necessary only when python-3.7 or cuda-10.2 is used, as it is bundled with all versions of torchvision?
> 
> @andfoy and why do we bundle those libraries as dynamic dependencies instead of compiling them in?

@malfet 
For cu102, I think it should be an known issue.
https://github.com/pytorch/vision/pull/4421#issuecomment-926021032

That's why I upgraded the unittest cuda version to 11.1

**Comment by fmassa** [comment] 2021-11-03 14:58
Hi @mszhanyi 

> In python3.7, we have to run conda install libpng. But it looks conda install libpng isn't necessary in Py38 or Py39 environment.

This is weird. `libpng` is a dependency for torchvision, so if it's not needed for Py38 or Py39 this means that it was transitively installed by some other dependency (maybe PIL?)

**Comment by andfoy** [comment] 2021-11-03 15:03
> and why do we bundle those libraries as dynamic dependencies instead of compiling them in?

It was easier when packaging the wheels, but statically compiling it into the image extension should fix these kind of issues indeed. However, OpenCV and other libraries also opt to dynamically link to libpng and other libraries.

**Comment by andfoy** [comment] 2021-11-03 15:05
> how did you install your python runtime? Via conda or downloaded from Python.org?

The local tests were done creating a Python 3.7 enviroment on conda, but everything installed from pip

**Comment by mszhanyi** [comment] 2021-11-04 10:51
> Hi @mszhanyi
> 
> > In python3.7, we have to run conda install libpng. But it looks conda install libpng isn't necessary in Py38 or Py39 environment.
> 
> This is weird. `libpng` is a dependency for torchvision, so if it's not needed for Py38 or Py39 this means that it was transitively installed by some other dependency (maybe PIL?)

open an issue for pillow
https://github.com/python-pillow/Pillow/issues/5813

**Comment by mszhanyi** [comment] 2021-11-08 12:08
It's wizard that in Python3.7, it ignores the libpng16.dll in the torchvision directory.
I run `import torch;import torchvsion` in the 3.7/3.8 environment
![image](https://user-images.githubusercontent.com/16190118/140739347-10b81e13-7f9c-4f0a-b56c-94d7a5d94227.png)

**Comment by peterjc123** [comment] 2021-11-08 12:50
I think the cause of this problem is quite clear. First, In PyTorch, we use `LoadLibraryEx` and then `LoadLibrary` to load in the dependencies, but in torchvision, it relies on `torch.ops.load_library`, which uses `ctypes.CDLL`. (It uses `LoadLibrary` as the underlying API.) The behavior is inconsistent. Second, in PyTorch, we use `AddDllDirectory` and `PATH` for dependency resolving, but we do nothing when `torch.ops.load_library` is called. Actually, we should do the same, that is to add the directory containing the DLLs for dependency search.

**Comment by malfet** [comment] 2021-11-10 06:40
@peterjc123 thank you very much for the detailed explanation. Looks like loading bundled DLLs never worked on Windows for python-3.6 and 3.7, and it works on 3.8 thanks to the following call:
https://github.com/pytorch/vision/blob/031e129b5590ec9619962ba44254405fd9ec90c8/torchvision/_internally_replaced_utils.py#L40-L41

**Comment by malfet** [comment] 2021-11-10 06:53
Filed a followup issue https://github.com/pytorch/vision/issues/4894 that nvjpeg is not bundled into the windows wheels
Another problem with nvjpeg integration, is that CUDA-11.3 torchvision wheel packages (and perhaps conda ones as well) are compiled without dependency on nvjpeg.

**Closed** 2021-12-13 21:58 UTC
Labels: windows
