### ISSUE TITLE
Cannot pip install torchvision==0.8.0+cu110

### ISSUE THREAD

**Issue by rsdmse** [pytorch/vision#2912] opened 2020-10-27 19:57 UTC
## 🐛 Bug

Cannot pip install torchvision==0.8.0+cu110

## To Reproduce

1. Copy command from pytorch website.
1. `pip install torch==1.7.0+cu110 torchvision==0.8.0+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`
1. Error message as follows

```
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.0+cu110 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.0, 0.4.0+cpu, 0.4.0+cu92, 0.4.1, 0.4.1+cpu, 0.4.1+cu100, 0.4.1+cu92, 0.4.2, 0.4.2+cpu, 0.4.2+cu100, 0.4.2+cu92, 0.5.0, 0.5.0+cpu, 0.5.0+cu100, 0.5.0+cu92, 0.6.0, 0.6.0+cpu, 0.6.0+cu101, 0.6.0+cu92, 0.6.1, 0.6.1+cpu, 0.6.1+cu101, 0.6.1+cu92, 0.7.0, 0.7.0+cpu, 0.7.0+cu101, 0.7.0+cu92, 0.8.0)
ERROR: No matching distribution found for torchvision==0.8.0+cu110
```

## Expected behavior

0.8.0+cu110 should be listed in https://download.pytorch.org/whl/torch_stable.html but it's not.

**Comment by seemethere** [comment] 2020-10-27 20:14
Transferred this issue to `pytorch/vision` since it has to do with `pytorch/vision`

**Comment by seemethere** [comment] 2020-10-27 20:35
Currently working on this, will have to issue a `v0.8.1` to resolve this though.

**Comment by rsdmse** [comment] 2020-10-27 20:38
Thanks for your help. Just wanted to check - would it be ok to install the default torchvision 0.8.0 with torch 1.7.0+cu110?

**Comment by seemethere** [comment] 2020-10-27 20:45
Yes you can install with `pip install -f https://download.pytorch.org/whl/cu110/torch_stable.html torch==1.7.0+cu110 torchvision==0.8.0`

**Comment by seemethere** [comment] 2020-10-27 21:20
This should be resolved now, you can use:
```
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by pkuppens** [comment] 2020-11-25 07:58
Has this problem reappeared??

It worked for me in the past, but today, no luck.

Context:
Working on Windows with Visual Studio Code, Jupyter Notebook, on a Python 3.9.0 based virtualenv.
I import numpy 1.19.3 first (because of fmod bug in Windows), and then try both versions you mention:

```
!pip install numpy==1.19.3
!pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
!pip install -f https://download.pytorch.org/whl/cu110/torch_stable.html torch==1.7.0+cu110 torchvision==0.8.0
```

Results in:

```
Requirement already satisfied: numpy==1.19.3 in e:\cart-tech\unetcart\.venv\lib\site-packages (1.19.3)
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.7.0+cu110 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.7.0+cu110
Looking in links: https://download.pytorch.org/whl/cu110/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cu110 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.7.0+cu110
```

I also tried from a terminal inside the virtualenv.

(Related question, I'm on CUDA 11.1, is that OK/backward compatible?)

**Comment by fmassa** [comment] 2020-11-27 10:21
Actually, @pkuppens this is a duplicate of https://github.com/pytorch/vision/issues/3046

From @vfdev-5 comment there:
> yes, it is related to Python 3.9. The binaries for Pytorch, Torchvision and others are only available for Python 3.6, 3.7 and 3.8.

As such, I'm closing as a duplicate. We will be adding Python 3.9 binaries for PyTorch / torchvision soon, and https://github.com/pytorch/vision/pull/3041 is a step towards this direction.

**Closed by fmassa** 2020-11-27 10:21 UTC

**Comment by HGamalElDin** [comment] 2021-01-20 10:32
> Yes you can install with `pip install -f https://download.pytorch.org/whl/cu110/torch_stable.html torch==1.7.0+cu110 torchvision==0.8.0`

please how to append this to the requirments.txt file? as it always raises (ERROR: Invalid requirement: 'torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio===0.7.2' (from line 12 of E:\requirements.txt)

**Comment by vfdev-5** [comment] 2021-01-20 10:34
@HGamalElDin try something like 
```bash
pip install -r requirements.txt -f https://download.pytorch.org/whl/cu110/torch_stable.html 
```

**Comment by HGamalElDin** [comment] 2021-01-20 10:45
> @HGamalElDin try something like
> 
> ```shell
> pip install -r requirements.txt -f https://download.pytorch.org/whl/cu110/torch_stable.html 
> ```

thank you, this works for me:
Adding in the file,
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.7.1+cu101 
torchvision==0.8.2+cu101 
torchaudio===0.7.2

**Comment by kumar-akshay324** [comment] 2022-01-14 18:45
If the torchvision version has been updated, can the website be updated to reflect these changes please - https://pytorch.org/get-started/previous-versions/#linux-and-windows-9

**Comment by Ynjxsjmh** [comment] 2023-02-13 02:51
I use `nvcc` to check my CUDA compiler version

```
$ /usr/local/cuda/bin/nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

Since it's `11.0` so I just search `CUDA 11.0` in https://pytorch.org/get-started/previous-versions/ page, it gives 4 results, for v1.7.0, there are conda and pip installation commands which give the `torchvision` not found error, hope this can be fixed

```
$ conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=11.0 -c pytorch
$ pip install torch==1.7.0+cu110 torchvision==0.8.0+cu110 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by hiepbk** [comment] 2024-04-18 23:46
> > Yes you can install with `pip install -f https://download.pytorch.org/whl/cu110/torch_stable.html torch==1.7.0+cu110 torchvision==0.8.0`
> 
> please how to append this to the requirments.txt file? as it always raises (ERROR: Invalid requirement: 'torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio===0.7.2' (from line 12 of E:\requirements.txt)

You can add --find-links https://download.pytorch.org/whl/torch_stable.html in your requirement.txt
