### ISSUE TITLE
MNIST and FashionMNIST raw and processed folders point to the same localtion

### ISSUE THREAD

**Issue by dizcza** [pytorch/vision#599] opened 2018-09-10 11:23 UTC
FashionMNIST inherits `raw_folder` and `processed_folder` from MNIST without a change. If you download MNIST and then try to download FashionMNIST in the same root folder, it'll say it's already downloaded while, in fact, it's not. After that FashionMNIST just uses MNIST data.

For a quick fix, make them as properties that depend on `__class__.__name__`. A better change would create parent folder with the class name. The user has no idea to what dataset 'raw' and 'processed' folders belong if he/she looks at his './data' dir unless he goes through all dataset implementations in torchvision.

**Comment by fmassa** [comment] 2018-09-11 13:33
Nice catch!
Could you send a PR fixing this? I think I have already seen this error pointed out before, but I couldn't reproduce it. Now I know where it comes from :-)

**Comment by vfdev-5** [comment] 2018-09-17 19:27
Can be closed

**Comment by soumith** [comment] 2018-09-17 19:35
closed via #601

**Closed by soumith** 2018-09-17 19:35 UTC
Labels: bug
